In [ ]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "kr-vs_kp OpenML.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "37qQSshhfeXx",
        "outputId": "c4786cec-3f54-4dbc-e63a-05ceef2b630c",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "!pip install -i https://test.pypi.org/simple/ all-in-one-ml==0.0.3"
      ],
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Looking in indexes: https://test.pypi.org/simple/\n",
            "Collecting all-in-one-ml==0.0.3\n",
            "  Downloading https://test-files.pythonhosted.org/packages/28/79/5a421fa17e3e9a8b1cfa6ea4d65ba5d97865efbdf0b4dc99d7e52ef3849f/all_in_one_ml-0.0.3.tar.gz\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from all-in-one-ml==0.0.3) (1.1.3)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from all-in-one-ml==0.0.3) (1.18.5)\n",
            "Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (from all-in-one-ml==0.0.3) (0.0)\n",
            "Requirement already satisfied: keras in /usr/local/lib/python3.6/dist-packages (from all-in-one-ml==0.0.3) (2.4.3)\n",
            "Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from all-in-one-ml==0.0.3) (0.11.0)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from all-in-one-ml==0.0.3) (3.2.2)\n",
            "Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas->all-in-one-ml==0.0.3) (2.8.1)\n",
            "Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->all-in-one-ml==0.0.3) (2018.9)\n",
            "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn->all-in-one-ml==0.0.3) (0.22.2.post1)\n",
            "Requirement already satisfied: h5py in /usr/local/lib/python3.6/dist-packages (from keras->all-in-one-ml==0.0.3) (2.10.0)\n",
            "Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.6/dist-packages (from keras->all-in-one-ml==0.0.3) (1.4.1)\n",
            "Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from keras->all-in-one-ml==0.0.3) (3.13)\n",
            "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->all-in-one-ml==0.0.3) (2.4.7)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->all-in-one-ml==0.0.3) (0.10.0)\n",
            "Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->all-in-one-ml==0.0.3) (1.2.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas->all-in-one-ml==0.0.3) (1.15.0)\n",
            "Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn->all-in-one-ml==0.0.3) (0.17.0)\n",
            "Building wheels for collected packages: all-in-one-ml\n",
            "  Building wheel for all-in-one-ml (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for all-in-one-ml: filename=all_in_one_ml-0.0.3-cp36-none-any.whl size=3868 sha256=0b03fb76fa8ff27613f1897395ffd49ff4d4d1d905c15648c4901ca2219036f7\n",
            "  Stored in directory: /root/.cache/pip/wheels/26/4f/f4/d595e3f4e73e8a49c62b9e2e99856618444f8d4c938d9c1b28\n",
            "Successfully built all-in-one-ml\n",
            "Installing collected packages: all-in-one-ml\n",
            "Successfully installed all-in-one-ml-0.0.3\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ml8MbuC5gx18"
      },
      "source": [
        "from all_in_one_ml import beginner\n",
        "from sklearn import datasets\n",
        "import pandas as pd"
      ],
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "umWGVnt1oMd7"
      },
      "source": [
        "data = datasets.fetch_openml('kr-vs-kp')"
      ],
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "AmgKpVoor65x"
      },
      "source": [
        "df = pd.DataFrame(data.data,columns = data.feature_names)\n",
        "df['class'] = data.target"
      ],
      "execution_count": 4,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "OClnvuW3tSf7",
        "outputId": "842d20ba-0fd1-4ad1-a005-232c51a5cc12",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 222
        }
      },
      "source": [
        "df.head()"
      ],
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>bkblk</th>\n",
              "      <th>bknwy</th>\n",
              "      <th>bkon8</th>\n",
              "      <th>bkona</th>\n",
              "      <th>bkspr</th>\n",
              "      <th>bkxbq</th>\n",
              "      <th>bkxcr</th>\n",
              "      <th>bkxwp</th>\n",
              "      <th>blxwp</th>\n",
              "      <th>bxqsq</th>\n",
              "      <th>cntxt</th>\n",
              "      <th>dsopp</th>\n",
              "      <th>dwipd</th>\n",
              "      <th>hdchk</th>\n",
              "      <th>katri</th>\n",
              "      <th>mulch</th>\n",
              "      <th>qxmsq</th>\n",
              "      <th>r2ar8</th>\n",
              "      <th>reskd</th>\n",
              "      <th>reskr</th>\n",
              "      <th>rimmx</th>\n",
              "      <th>rkxwp</th>\n",
              "      <th>rxmsq</th>\n",
              "      <th>simpl</th>\n",
              "      <th>skach</th>\n",
              "      <th>skewr</th>\n",
              "      <th>skrxp</th>\n",
              "      <th>spcop</th>\n",
              "      <th>stlmt</th>\n",
              "      <th>thrsk</th>\n",
              "      <th>wkcti</th>\n",
              "      <th>wkna8</th>\n",
              "      <th>wknck</th>\n",
              "      <th>wkovl</th>\n",
              "      <th>wkpos</th>\n",
              "      <th>wtoeg</th>\n",
              "      <th>class</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>won</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>won</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>won</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>won</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>1.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>won</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "   bkblk  bknwy  bkon8  bkona  bkspr  ...  wknck  wkovl  wkpos  wtoeg  class\n",
              "0    1.0    1.0    1.0    1.0    1.0  ...    1.0    0.0    0.0    0.0    won\n",
              "1    1.0    1.0    1.0    1.0    0.0  ...    1.0    0.0    0.0    0.0    won\n",
              "2    1.0    1.0    1.0    1.0    0.0  ...    1.0    0.0    0.0    0.0    won\n",
              "3    1.0    1.0    1.0    1.0    1.0  ...    1.0    0.0    0.0    0.0    won\n",
              "4    1.0    1.0    1.0    1.0    1.0  ...    1.0    0.0    0.0    0.0    won\n",
              "\n",
              "[5 rows x 37 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 5
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4sCHISIbtkqV"
      },
      "source": [
        "x = df.drop(columns=['class'])\n",
        "y = df['class']"
      ],
      "execution_count": 6,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "prY8p-M_kSp2",
        "outputId": "918c84a5-b38d-414e-9120-0b5abe916cbe",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "x_hot,y_hot = beginner.one_hot(x,y,cat='~')\n",
        "print(x_hot,y_hot)"
      ],
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "      bkblk_0.0  bkblk_1.0  bknwy_0.0  ...  wkpos_1.0  wtoeg_0.0  wtoeg_1.0\n",
            "0             0          1          0  ...          0          1          0\n",
            "1             0          1          0  ...          0          1          0\n",
            "2             0          1          0  ...          0          1          0\n",
            "3             0          1          0  ...          0          1          0\n",
            "4             0          1          0  ...          0          1          0\n",
            "...         ...        ...        ...  ...        ...        ...        ...\n",
            "3191          1          0          0  ...          1          1          0\n",
            "3192          1          0          0  ...          1          1          0\n",
            "3193          1          0          0  ...          1          1          0\n",
            "3194          1          0          0  ...          1          1          0\n",
            "3195          1          0          0  ...          1          1          0\n",
            "\n",
            "[3196 rows x 73 columns]       nowin  won\n",
            "0         0    1\n",
            "1         0    1\n",
            "2         0    1\n",
            "3         0    1\n",
            "4         0    1\n",
            "...     ...  ...\n",
            "3191      1    0\n",
            "3192      1    0\n",
            "3193      1    0\n",
            "3194      1    0\n",
            "3195      1    0\n",
            "\n",
            "[3196 rows x 2 columns]\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Bi7EqujclEPp",
        "outputId": "70323153-9b78-46d4-8eba-2a7eb0ed9313",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "x_train,x_test,y_train,y_test = beginner.split_dataset(x_hot,y_hot,0.2,8)"
      ],
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "(2556, 73) (2556, 2) (640, 73) (640, 2)\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "u2sDazVOlP0o",
        "outputId": "8895b52b-38b3-48e4-cb81-6ee852988c8a",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 222
        }
      },
      "source": [
        "x_train.head()"
      ],
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>bkblk_0.0</th>\n",
              "      <th>bkblk_1.0</th>\n",
              "      <th>bknwy_0.0</th>\n",
              "      <th>bknwy_1.0</th>\n",
              "      <th>bkon8_0.0</th>\n",
              "      <th>bkon8_1.0</th>\n",
              "      <th>bkona_0.0</th>\n",
              "      <th>bkona_1.0</th>\n",
              "      <th>bkspr_0.0</th>\n",
              "      <th>bkspr_1.0</th>\n",
              "      <th>bkxbq_0.0</th>\n",
              "      <th>bkxbq_1.0</th>\n",
              "      <th>bkxcr_0.0</th>\n",
              "      <th>bkxcr_1.0</th>\n",
              "      <th>bkxwp_0.0</th>\n",
              "      <th>bkxwp_1.0</th>\n",
              "      <th>blxwp_0.0</th>\n",
              "      <th>blxwp_1.0</th>\n",
              "      <th>bxqsq_0.0</th>\n",
              "      <th>bxqsq_1.0</th>\n",
              "      <th>cntxt_0.0</th>\n",
              "      <th>cntxt_1.0</th>\n",
              "      <th>dsopp_0.0</th>\n",
              "      <th>dsopp_1.0</th>\n",
              "      <th>dwipd_0.0</th>\n",
              "      <th>dwipd_1.0</th>\n",
              "      <th>hdchk_0.0</th>\n",
              "      <th>hdchk_1.0</th>\n",
              "      <th>katri_0.0</th>\n",
              "      <th>katri_1.0</th>\n",
              "      <th>katri_2.0</th>\n",
              "      <th>mulch_0.0</th>\n",
              "      <th>mulch_1.0</th>\n",
              "      <th>qxmsq_0.0</th>\n",
              "      <th>qxmsq_1.0</th>\n",
              "      <th>r2ar8_0.0</th>\n",
              "      <th>r2ar8_1.0</th>\n",
              "      <th>reskd_0.0</th>\n",
              "      <th>reskd_1.0</th>\n",
              "      <th>reskr_0.0</th>\n",
              "      <th>reskr_1.0</th>\n",
              "      <th>rimmx_0.0</th>\n",
              "      <th>rimmx_1.0</th>\n",
              "      <th>rkxwp_0.0</th>\n",
              "      <th>rkxwp_1.0</th>\n",
              "      <th>rxmsq_0.0</th>\n",
              "      <th>rxmsq_1.0</th>\n",
              "      <th>simpl_0.0</th>\n",
              "      <th>simpl_1.0</th>\n",
              "      <th>skach_0.0</th>\n",
              "      <th>skach_1.0</th>\n",
              "      <th>skewr_0.0</th>\n",
              "      <th>skewr_1.0</th>\n",
              "      <th>skrxp_0.0</th>\n",
              "      <th>skrxp_1.0</th>\n",
              "      <th>spcop_0.0</th>\n",
              "      <th>spcop_1.0</th>\n",
              "      <th>stlmt_0.0</th>\n",
              "      <th>stlmt_1.0</th>\n",
              "      <th>thrsk_0.0</th>\n",
              "      <th>thrsk_1.0</th>\n",
              "      <th>wkcti_0.0</th>\n",
              "      <th>wkcti_1.0</th>\n",
              "      <th>wkna8_0.0</th>\n",
              "      <th>wkna8_1.0</th>\n",
              "      <th>wknck_0.0</th>\n",
              "      <th>wknck_1.0</th>\n",
              "      <th>wkovl_0.0</th>\n",
              "      <th>wkovl_1.0</th>\n",
              "      <th>wkpos_0.0</th>\n",
              "      <th>wkpos_1.0</th>\n",
              "      <th>wtoeg_0.0</th>\n",
              "      <th>wtoeg_1.0</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>1897</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>37</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2511</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>940</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2638</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "      bkblk_0.0  bkblk_1.0  bknwy_0.0  ...  wkpos_1.0  wtoeg_0.0  wtoeg_1.0\n",
              "1897          0          1          0  ...          0          1          0\n",
              "37            0          1          0  ...          1          1          0\n",
              "2511          1          0          0  ...          1          1          0\n",
              "940           0          1          0  ...          1          1          0\n",
              "2638          0          1          0  ...          1          1          0\n",
              "\n",
              "[5 rows x 73 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ThF2tyIAlQY7",
        "outputId": "bc78f896-bc9e-4a33-c4ad-6f8ea7524588",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 202
        }
      },
      "source": [
        "y_train.head()"
      ],
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>nowin</th>\n",
              "      <th>won</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>1897</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>37</th>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2511</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>940</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2638</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "      nowin  won\n",
              "1897      0    1\n",
              "37        0    1\n",
              "2511      1    0\n",
              "940       1    0\n",
              "2638      1    0"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 10
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "GSOINIB3lT3N",
        "outputId": "93fe7d25-9bee-4655-f7aa-e931df487875",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "model,history = beginner.build_compile_fit_model(x_train,y_train,'classification',30,3,[100,100,100],['relu','relu','relu'])"
      ],
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Model: \"sequential\"\n",
            "_________________________________________________________________\n",
            "Layer (type)                 Output Shape              Param #   \n",
            "=================================================================\n",
            "dense (Dense)                (None, 100)               7400      \n",
            "_________________________________________________________________\n",
            "dense_1 (Dense)              (None, 100)               10100     \n",
            "_________________________________________________________________\n",
            "dense_2 (Dense)              (None, 100)               10100     \n",
            "_________________________________________________________________\n",
            "dense_3 (Dense)              (None, 2)                 202       \n",
            "=================================================================\n",
            "Total params: 27,802\n",
            "Trainable params: 27,802\n",
            "Non-trainable params: 0\n",
            "_________________________________________________________________\n",
            "Epoch 1/30\n",
            "64/64 [==============================] - 0s 5ms/step - loss: 0.4257 - accuracy: 0.8019 - val_loss: 0.1957 - val_accuracy: 0.9453\n",
            "Epoch 2/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.1438 - accuracy: 0.9486 - val_loss: 0.0884 - val_accuracy: 0.9668\n",
            "Epoch 3/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0942 - accuracy: 0.9609 - val_loss: 0.0606 - val_accuracy: 0.9785\n",
            "Epoch 4/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0674 - accuracy: 0.9755 - val_loss: 0.0714 - val_accuracy: 0.9746\n",
            "Epoch 5/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0406 - accuracy: 0.9848 - val_loss: 0.0534 - val_accuracy: 0.9805\n",
            "Epoch 6/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0382 - accuracy: 0.9858 - val_loss: 0.0334 - val_accuracy: 0.9883\n",
            "Epoch 7/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0388 - accuracy: 0.9848 - val_loss: 0.0284 - val_accuracy: 0.9902\n",
            "Epoch 8/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0285 - accuracy: 0.9897 - val_loss: 0.0181 - val_accuracy: 0.9961\n",
            "Epoch 9/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0133 - accuracy: 0.9966 - val_loss: 0.0246 - val_accuracy: 0.9922\n",
            "Epoch 10/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0109 - accuracy: 0.9976 - val_loss: 0.0377 - val_accuracy: 0.9902\n",
            "Epoch 11/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0204 - accuracy: 0.9902 - val_loss: 0.0158 - val_accuracy: 0.9902\n",
            "Epoch 12/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0266 - accuracy: 0.9907 - val_loss: 0.0224 - val_accuracy: 0.9883\n",
            "Epoch 13/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0093 - accuracy: 0.9966 - val_loss: 0.0208 - val_accuracy: 0.9941\n",
            "Epoch 14/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0071 - accuracy: 0.9976 - val_loss: 0.0221 - val_accuracy: 0.9902\n",
            "Epoch 15/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0045 - accuracy: 0.9990 - val_loss: 0.0131 - val_accuracy: 0.9941\n",
            "Epoch 16/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0171 - accuracy: 0.9932 - val_loss: 0.0129 - val_accuracy: 0.9980\n",
            "Epoch 17/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0098 - accuracy: 0.9966 - val_loss: 0.0356 - val_accuracy: 0.9844\n",
            "Epoch 18/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0136 - accuracy: 0.9946 - val_loss: 0.0768 - val_accuracy: 0.9688\n",
            "Epoch 19/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0399 - accuracy: 0.9868 - val_loss: 0.0193 - val_accuracy: 0.9941\n",
            "Epoch 20/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 0.9985 - val_loss: 0.0079 - val_accuracy: 0.9980\n",
            "Epoch 21/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000 - val_loss: 0.0084 - val_accuracy: 0.9961\n",
            "Epoch 22/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 9.2266e-04 - accuracy: 1.0000 - val_loss: 0.0063 - val_accuracy: 0.9980\n",
            "Epoch 23/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 6.2865e-04 - accuracy: 1.0000 - val_loss: 0.0055 - val_accuracy: 0.9980\n",
            "Epoch 24/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 4.6259e-04 - accuracy: 1.0000 - val_loss: 0.0057 - val_accuracy: 0.9980\n",
            "Epoch 25/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 3.6170e-04 - accuracy: 1.0000 - val_loss: 0.0054 - val_accuracy: 0.9980\n",
            "Epoch 26/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 3.1062e-04 - accuracy: 1.0000 - val_loss: 0.0050 - val_accuracy: 0.9980\n",
            "Epoch 27/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 2.6214e-04 - accuracy: 1.0000 - val_loss: 0.0053 - val_accuracy: 0.9980\n",
            "Epoch 28/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 2.3604e-04 - accuracy: 1.0000 - val_loss: 0.0047 - val_accuracy: 0.9980\n",
            "Epoch 29/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 2.0256e-04 - accuracy: 1.0000 - val_loss: 0.0044 - val_accuracy: 0.9980\n",
            "Epoch 30/30\n",
            "64/64 [==============================] - 0s 2ms/step - loss: 1.7846e-04 - accuracy: 1.0000 - val_loss: 0.0043 - val_accuracy: 0.9980\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "54fMbUdcllD6",
        "outputId": "3e1e8fa6-ec93-4da6-b786-44f6cc1eeb6f",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "source": [
        "beginner.get_accuracy(x_test,y_test,model)"
      ],
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "20/20 [==============================] - 0s 1ms/step - loss: 0.0094 - accuracy: 0.9953\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "KgB2aWjBlwZX",
        "outputId": "c3e1d1b9-ffe9-4770-c33e-c4c0372ec655",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 295
        }
      },
      "source": [
        "beginner.accuracy_vs_valaccuracy(model,history,30)"
      ],
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAZAAAAEWCAYAAABIVsEJAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nOzdd3hU1dbA4d9KKKGT0CE0hYv0ABFULCii2FBQKRbEgoWi2LEjXK9eRUU/FQWVJgoIF7AgCAoXr5UgvRdRQjMklEAS0tb3xzkJkzBJJmVS1/s883DqnnUmYVb23ufsLaqKMcYYk1sBRR2AMcaYkskSiDHGmDyxBGKMMSZPLIEYY4zJE0sgxhhj8sQSiDHGmDyxBGLyTUS+EZE7CvrYoiQie0Tkcj+Uu0JE7nGXbxWRb305Ng/v00RETohIYF5jNSYnlkDKKPfLJe2VKiLxHuu35qYsVb1KVacV9LHFkYiMFpGVXrbXFpFEEWnna1mqOlNVryiguDIkPFX9S1WrqmpKQZRvjDeWQMoo98ulqqpWBf4CrvPYNjPtOBEpV3RRFkufABeISPNM2wcCG1R1YxHEVGbY72PxYgnEZCAiPUQkUkSeFJGDwBQRCRaRr0QkSkSOuMuhHud4NssMEZH/ich499g/ROSqPB7bXERWikisiCwTkXdF5JMs4vYlxnEi8qNb3rciUttj/+0i8qeIRIvIM1l9PqoaCXwP3J5p12Bgek5xZIp5iIj8z2O9l4hsFZFjIvIOIB77zhaR7934DovITBGp6e6bATQBvnRrkE+ISDMR0bQvXBFpKCJfiEiMiOwUkaEeZY8RkTkiMt39bDaJSHhWn4GIvCUie0XkuIisFpGLPPYFisjTIrLLLWu1iDR297UVkaVuDIdE5Gl3+1QR+adHGT1EJNJjfY/7+7geOCki5dyaYNp7bBaRvpliHCoiWzz2dxaRx0VkXqbj3haRt7K6VpM9SyDGm/pACNAUuBfn92SKu94EiAfeyeb8bsA2oDbwKvCRiEgejv0U+A2oBYzhzC9tT77EeAtwJ1AXqAA8BiAibYCJbvkN3ffz+qXvmuYZi4i0AsLceHP7WaWVURv4D/AszmexC+jueQjwshtfa6AxzmeCqt5Oxlrkq17eYhYQ6Z5/E/AvEbnMY38f95iawBc5xLzKvd4Q95o/F5Egd98jwCDgaqA6cBcQJyLVgGXAYjeGFsB32X0mmQwCrgFqqmoyzudzEVADeBH4REQaAIjIzTifzWA3hj5ANE7tsbdH4i2HU3Ocnos4jCdVtVcZfwF7gMvd5R5AIhCUzfFhwBGP9RXAPe7yEGCnx77KgAL1c3MszpdvMlDZY/8nwCc+XpO3GJ/1WB8GLHaXnwdmeeyr4n4Gl2dRdmXgOHCBu/4SsDCPn9X/3OXBwC8exwnOF/49WZR7A7DG28/QXW/mfpblcJJNClDNY//LwFR3eQywzGNfGyA+F78/R4CO7vI24HovxwzyjDfTvqnAPz3WewCRma7trhxiWJv2vsAS4KEsjvsGGOouXwtsLoz/Y6X1ZTUQ402UqiakrYhIZRH5wG3iOQ6sBGpK1nf4HExbUNU4d7FqLo9tCMR4bAPYm1XAPsZ40GM5ziOmhp5lq+pJnL9YvXJj+hwY7NaWbsX9KzYPn1WazDGo57qI1BORWSKyzy33E5yaii/SPstYj21/Ao081jN/NkGSRX+DiDzmNg8dE5GjOLWAtFga49QOMstqu68y/OxFZLCIrBWRo24M7XyIAZza423u8m3AjHzEVOZZAjHeZB6i+VGgFdBNVasDF7vbs2qWKggHgBARqeyxrXE2x+cnxgOeZbvvWSuHc6YB/YFeQDXgy3zGkTkGIeP1/gvn59LeLfe2TGVmN6z2fpzPsprHtibAvhxiOoPb3/EEzrUHq2pN4JhHLHuBs72cuhc4K4tiT+LU6tLU93JM+vWJSFNgMjACqOXGsNGHGAAWAB3EuVvuWmBmFscZH1gCMb6ohtOWf1REQoAX/P2GqvonEAGMEZEKInI+cJ2fYpwLXCsiF4pIBWAsOf/f+AE4CkzCaf5KzGccXwNtRaSf+5f/g2T8Iq0GnACOiUgj4PFM5x8iiy9oVd0L/AS8LCJBItIBuBunFpNb1XCaFqOAciLyPE4/Q5oPgXEi0lIcHUSkFvAV0EBERolIRRGpJiLd3HPWAleLSIiI1AdG5RBDFZyEEgUgInfi1EA8Y3hMRLq4MbRwkw5uzXoubv+aqv6Vh8/AuCyBGF9MACoBh4FfcDpCC8OtwPk4zUn/BGYDp7I4Ns8xquomYDjOl8oBnDb9yBzOUZxmq6Zk7ITNUxyqehi4GXgF53pbAj96HPIi0Bnnr/2vcTrcPb0MPOs26Tzm5S0G4fSL7AfmAy+o6jJfYstkCc41bcdpBksgY/PSG8Ac4FucfqKPgEpu81kvnD8CDgI7gEvdc2YA63D6Or7F+TlnSVU3A68DP+MkzvZ4fFaq+jlOv9SnQCxOrSPEo4hp7jnWfJVP4nYmGVPsichsYKuq+r0GZEovEWkCbMW5seN4UcdTklkNxBRbInKuOM8/BIhIb+B6nL8mjckTEQnAudV4liWP/LOnOk1xVh+nqaYWTpPSA6q6pmhDMiWViFTBafL6E+hdxOGUCtaEZYwxJk+sCcsYY0yelIkmrNq1a2uzZs2KOgxjjClRVq9efVhV62S1v0wkkGbNmhEREVHUYRhjTIkiIn9mt9+asIwxxuSJJRBjjDF5YgnEGGNMnlgCMcYYkyeWQIwxxuSJXxOIiHwsIn+LiNd5ot2RMt8WZ4rN9SLS2WPfHSKyw33d4bG9i4hscM95O5uZ7owxxviRv2sgU8l+yICrcEYdbYkzdepEAI9hsLsBXYEXRCTYPWciMNTjPBuSwBhjioBfnwNR1ZUi0iybQ64HprtDY/8iIjXdeY17AEtVNQZARJbizGW8Aqiuqr+426fjTO35jd8uwhiTa3FJceyK2cXOmJ3sOrKL46ds3MKiMrLrSOpUyfJZwHwp6gcJG5FxLoFId1t22yO9bD+DiNyLU6uhSZMmBRexMT46lnCMXUfcL9GYXbSs1ZIbW99IaWl1PX7qODuid6RfY9pr15Fd7I/dn+FY8evklSY7t7S/pdQmEL9R1Uk4s8URHh5uI0aWIKpKYkoiFctVLOpQsqWqHI47nOEL1HP5cNzhM87p2qgrr1/xOhc2ufCMfampsHIl/PgjPPQQVM1qFvkilpoKT324hNc+jUBr7oR666DuJhrUrEWLkBZccfYVtAhuQYsQ53V2yNnUDKqZZXlxcbBhA6xbB9u3Q0pKIV5MGRDsx8+zqBPIPjLO+xzqbtuH04zluX2Fuz3Uy/GmBEhKSeLPY39y8MRBDp44yKETh9KXD548mGF7qqby6PmPMvbSsYWeSBJTEvnr2F+nY/PyOnTyEIdOHCIpNSn9PEFoXKMxLUJa0O+cfpwdcnb6l2izms2Yv2U+z3z/DBdNuYh+rfvx78v/TYuQFuzcCdOnO68/3YEjNmyAzz6D7CoriSmJqGqhfT47dsC0aTBpSjxR+68ErkzfV66cUuscoWkYtAuDjh2hYz2o4/GHryocPAhr1zrJYu1a57Vjh5OUAIKCoEKFQrmcMuOBB6BePf+U7ffh3N0+kK9UtZ2XfdcAI4CrcTrM31bVrm4n+mqcKTwBfge6qGqMiPyGM1/0r8Ai4P9UdVF2MYSHh6uNheUfGzfCzJlw4YVw5ZVQLos/Sb7b/R1DvxzKH0f/yLA9QAKoW6Uu9avWT3/Vq1KP/bH7mbF+Bh3rdeSTfp/Qru4Zvz4FLlVTmb5uOs98/8wZTTCBEpgeZ72q9ZxYqzjxnh1yNmcHn03z4OYElQvK9j3ikuJ44+c3eHnZe5xa14d6O59g/+azEIFeveCOO2DnTnjhBXj7bRg5MuP5JxNPsmjHIuZtmcfXO74mITmB1rVb07F+R8LqhRFWP4yO9TtSu3LtAvlMjh6F2bOdxPHzzxAQoHD2Mhpf/D0///tpYqOrZUgI69bBPo8/6Ro2hLAwSEpy9kdFnd7XrJmzr2PH0/82a5Z90jSFS0RWq2p4lvv9mUBE5DOcmkRtnIlcXgDKA6jq++4tuO/g3EkVB9ypqhHuuXcBT7tFvaSqU9zt4Th3d1XC6TwfqTlchCWQgnfwIDz/PHz00em/HuvVg1tvdb4EO3Rwth1NOMrj3z7Oh2s+pGVIS57s/iSNazROTxa1KtUiMCDQ63t8ue1L7vnyHo4lHOPlni/z0HkPESD+uXHw+z++59FvH2XtwbV0bdSVB8IfoFG1RukJI7s4fZWSAkuXOl/GCxYoCQkCdTYT1GUOTzzQkKevvoOK5SqSmgo33ACLFztNWq3DjvHV9q+Yt2Uei3cuJj45njqV63DDOTdQu3Jt1h1ax9qDazMkvUbVGjnJpF5HwuqHEd4wnObBzX2KMznZiXPqVFi4EE6dgjZt4JqbDvNhSg9q1onjp7t/on7V+l7PP3w4Y0JZuxbKl8+YLDp0gJpZt2qZYiKnBIKqlvpXly5d1BSMEydUx45VrVJFtXx51VGjVA8cUF2wQLVvX2cbqIaFqd791AatN6a9BrwYoE98+4TGJcbl+v0OnTikfT7ro4xBe07rqXuP7S3Q69kStUWv/fRaZQza9M2m+vEvc/Rf/0rR555T3bq1YN5j40bVxx9XbdDA+WyCg1WHDVP97TfVdQfW65UzrlTGoGe9dZZ+vulzTU1N1V37YrR2o+MaFPK3lh/dUBmDNhjfQId/PVy/3/29JqUknfE+f5/4W5fuWqrjfxyvt/3nNm33XjsNfDFQGYMyBn1k8SN6KvlUtrF++KFq/fpOnCEhqiNGqK5apbr/+AFtPqG51n61tm4/vL1gPhhT7AERms13a5F/uRfGyxJI/iUnq06ZotqwofNb06+f6o4dZx4XFaX68vjjGnzWTgVVAhL1ol5HdO5c1YSEvL13amqqTl49Wau8VEVrvlJTP13/ab6uRdX5sh321TANfDFQq79cXV/+76v63vuJ6V+eAQHOv+edp/ree6oxMbkrPypK9e23Vbt0ccoJDFS97jrN8nNYvGOxtnuvnTIGbfF2Cy03tpxyX5hSLl6bdN6qK//4UVNSU3J9nfFJ8bp6/2od/vVwZQzadXJX3R2z2+uxMTGqQUGq556r+p//qJ5yc83xhOPa+YPOWvmlyvpr5K+5jsGUXJZALIHk27JlTo0CVLt2Vf3hB+/Hpaam6sz1M7XWv2tphXEVdMTUifrIo8npf3mHhKjeeqvq+PGqS5eq/v137uLYGb1Tz//wfGUMOmjuII2Jy+W3ujpfqK/88IpW+1c1DXwxUId/PVxnLzyi7ds7MZ5/vupPP6nu36/62muq7do52ytUUL35ZtWvvlJNOvOPf1V1vnC91cTefFP10KGcY0tKSdLJqyfrJVMu0SeXPqmr9q3SSZNSFVSffz7Xl3qGeZvnaY2Xa2iNl2vovM3zztj/xhtOzGvWeFxT8intNb2XBr4YqIu2L8p/EKZEsQRiCSTPNm1SveYa57ekaVPVzz5TTcnij+C9x/bqNTOvUcag3SZ3001/b0rfl5Sk+s03qoMGqTZq5JSX9mrYUPXqq1Wfekp19myn2Sg5OeuYklKS9J///aeWG1tOQ98I1WW7lnk9LiU1RY8nHNcDsQd0R/QOXXNgjU5bO02bvtlUGYNe9+l1unDlLr3ySieO5s1V58xRTU3NWE5qqurq1aoPPqhau7ZzbL16qo88orpuXc778ys1VXXIEFUR5zPMr90xu7Xr5K7KGHTE1yM0PileVZ2fa8uWqhdccPrYlNQUvXXercoYdMqaKfl/c1Pi5JRA/H4XVnFgneg5U4U9e053ev7+Oyxa5DyL8Mwzzt1AQV5uMEpJTeGjNR/x+NLHSU5N5qXLXmJk15HZdjh762TdssXpvAWoXBlat/b+fmlOJMayPXo78Unx1KyVTIVGW5D660iuu5q4KpuJT47zel6n+p14ptP/seTD7nz0EVSvDs89B8OHQ8Uc7oZNTIRvvnE6wb/6yrmzqF49OHTIufX0+uudGwiyuxstL+Li4PzzITLS+bk0bZq/8hJTEnn6u6d5/efX6VS/E3NunsMfq1twxRXwySfOjRAATyx9gtd+eo2XLnuJpy96OvtCTalUpHdhFReWQDJKSIBNmzJ+ia9bB8eOOftF4B//gKuucpJHbS93hCYkJzBt7TTG/zyenTE7uaz5ZUy+bjJnBZ+Vp5hOnYLNm0/HtHXr6YSSlRRNYXfMHxw+VJ64g6GgTtKqWCWeemf/TeN/RNP8nOP8o20crVonE1yxFj/POZ9XXw0gMdFJGs89ByEhuY83OhpmzYIVK6BnTxgwAIKDczwtz3bsgPBwaNUKfvgh52Tniy+3fcmQhUNISkmi1bLN7FkfSmSkU/aEXybw8JKHGRY+jHeufqfUPD1vcsfuwrImrHTffafaqZPToZvWhFSlitNs8cADqh98oPrLL86dVlk5En9E/7XyX1rvtXrKGPTcSefq3E1zNTVz208hO3lS9ddfnWsYNsy5pqpVT19nYKBq9erO8o03er8BoLibN8+Jf9iwgivzr6N/aZfXblAkWcNuXKRxiXE6a8MsZQzab3Y/TU7Jpj3RlHrk0IRV1E+im0KQkgJjx8K4cdCiBYweffqe/LPPhgAfHq3Yd3wfE36ZwAerPyA2MZYrz76SJ7s/SY9mPYrFX6eVK0PXrs4rTWoq7N59ulazdy/cc4/z0GNJ1K8fPPoovP46dO8Ot9yS/zIb12jMFUfmshphbegDdJ5Uid1HdnNRk4uY2W9mvp99MaWbNWGVcpH7Uhl4Swo/rizPFf32c9voX2hQq3r6g3whlUKyfThv6+GtvPbja8xYP4MUTWFA2wE80f0JwuqHFeJVmDRJSXDZZU5fyG+/Qdu2+SsvMRGaNIFzz4Xhby7m9vm3U69KPX648weCK/mxTc6UCNYHQulPIFuitrBs9zIOnTyUYbymPRHnED3zTUiqDNcMg7DpZ5xbLqBcxqFEqjhPXterUo///vlfFmxdQMVyFbm70908ev6jPj/NbPxn/37o3Nl5knvVKqhWLe9lzZ4NAwc6N0xcdRWcSDxBoARSqXylggvYlFiWQCjdCeTLbV8yYO4A4pPjCZRA58u/UijHFj3K7q/6U6f5AYa+vIwObSuk1ziOJBw5c0DDk6fXD508RHJqMsFBwQw/dzgju42kbpW6RX2pxkNa5/3Agc5YZHl1ySVO097Onb41ZZqyJacEYn0gJdgHER8wbNEwOjfozJyb5tC0ZlMi9wYwcCCs+Rnuuw/efLMBlSrdnqtyUzWV6LhoqlWsluPggKZo9OjhDLj4wgtO38iNN+a+jI0bnbG2Xn3VkofJG/u1KYFUlWe/f5b7v76fq1pcxYo7VtA8uDlffhFAWJjzxTBrFrz/PlTKQ0tEgARQp0odSx7F3FNPQZcuznDdnqPc+mriROeW3TvvLPjYTNlgCaSESUxJZMjCIbz0w0sM7TyUBQMXUE6rMGqUM4Jr8+ZOB+uAAUUdqfG38uWdEXOPHYNhw5wbln0VG+vMPzJggPfnfIzxhSWQEuT4qeNc8+k1TF83nXGXjuP9az5g6ZJydO4Mb70FDz4IP/3k3KpryoZ27eDFF2HuXJgzx/fzPvkETpxwEo8xeWWd6IUsJcX5SzG3Q13sj93PVTOvYnPUZiZfN5lOMoTHH3fmbWjRAt58E6691j8xm+ItOdl5LmTnTmeEgfrep+lIpwrt2ztDxaxaZRM4mazl1IluNZBCdPKkc9dLvXrOMBq//eZbs8Omvzdx3ofnsfvIbqb3XMYP/zeETp1g9WqYMMH50rDkUXaVK+eMz3XyJNx/f86/Uz/84PzODBtmycPkj18TiIj0FpFtIrJTREZ72d9URL4TkfUiskJEQt3tl4rIWo9Xgojc4O6bKiJ/eOwrEU+0JSc77c0//wwXXAAffwzdujkzvb3ySsZpQD39d89/uXDKhZyKL88th7dzT69LmDEDHnnE+YvzoYdsDmkD55wDL73kzCCY0229773nPEMycGDhxGZKsezGOcnPCwgEdgFnARWAdUCbTMd8DtzhLl8GzPBSTggQA1R216cCN+UmlqIeCys1VfWuu5xxjCZOdLYdPao6aZJq9+7OdhHVXr1UZ850xnVSVZ21YZaWfzFIG9zyjNatn6Sg2r+/6q5dRXctpvhKTnZ+n2rWVN23z/sxBw6oliun+vDDhRubKZkoqvlAgPOBJR7rTwFPZTpmE9DYXRbguJdy7gVmeqyXuATy7LPOJ/3cc97379jh7Gva1DmuWjXVK276U7n+Dq0cujN9ZryffirUsE0JtH27aqVKzhwr3sa3HDfO+R3btq3wYzMlT1EmkJuADz3WbwfeyXTMp8BD7nI/QIFamY75HrjWY30qsA1YD7wJVMzi/e8FIoCIJk2a+OXD9cV77zmf8t13e/8P7SklRXX5ctX+t55UKpxQUG3WPMXrREfGZOWtt5zfuY8/zrg9KUk1NNSp6Rrji5wSSFF3oj8GXCIia4BLgH1AStpOEWkAtAeWeJzzFHAOcC5O89aT3gpW1UmqGq6q4XXq1PFT+Nn7z3+czvJrr3Ue6supwzIgAC6+JJWjvftScXQTpi3cw9YtAdx8s3V2Gt+NGOHcrDFqlDNMSZqvvnImpbJbd01B8WcC2Qc09lgPdbelU9X9qtpPVTsBz7jbjnoc0h+Yr6pJHucccJPjKWAK0JVi6IcfnOG2u3VzBqzz9bbdt355i293fcuE615icJ9mBTJxkClbAgKcmzRSUpzh69W9K+u99yA01O7YMwXHnwlkFdBSRJqLSAVgIPCF5wEiUlskfSzxp4CPM5UxCPgs0zkN3H8FuAHY6IfY82XjRujTB5o1c/7qq1zZt/PWHlzL6O9Gc32r67mvy31+jdGUbmedBa+9Bt9+C5Mnw/btzjND991XsNPtmrLNb79KqposIiNwmp8CgY9VdZOIjMVpV/sC6AG8LCIKrASGp50vIs1wajD/zVT0TBGpg9Ppvha431/XkBd790Lv3s4YVIsXQ61avp0XlxTHoHmDqFWpFh/2+bBYTNJkSrb77oN585xJqHr3dhLHPfcUdVSmNLEn0QtQTAxcdJHTzrxypTPjn68e+OoB3l/9PktvX8rlZ13uvyBNmfLnn85T57GxznNIs2YVdUSmJLEn0QtJfDxcf73zcN+CBblLHgu2LuD91e/z+AWPW/IwBappU2ectAoVnLHSjClIVgMpACkpcNNNzlPAs2ZB//6+n7vv+D46vN+BZjWb8fPdP1Mh0B4rNwUvNjZ/MxeasskmlCoEM2c6tY433shd8kjVVO5YcAcJyQl82u9TSx7Gbyx5GH+wBJJPKSnOGEQdOjjjUuXG6z+9znd/fMfk6ybTqnYr/wRojDF+Ygkknz7/3LlFcs6c3E0Lunr/ap75/hlubH0jd3e6238BGmOMn1gfSD6kpjo1D1XYsMH3BHIy8SSdJ3UmLimOdfevI6RSSIHHZowx+WV9IH40f74zr8LMmbmrfYxaPIod0Tv4/o7vLXkYY0osu403j1Rh3Dho2TJ384/P3TyXD9d8yOgLR9OjWQ+/xWeMMf5mNZA8+vJLWLcOpk6FwEDfzll7cC13LryTro268mKPF/0anzHG+JvVQPIgrfbRvLkzYKIvIo9Hcs2n1xAcFMyCAQsoH1jev0EaY4yfWQ0kD5YsgYgIZ5C68j7kgdhTsVz32XXEnorlx7t+pEG1Bv4P0hhj/MwSSC6pwtix0KQJDB6c8/HJqckMnDeQDYc28PUtX9O+Xnv/B2mMMYXAEkguff89/PwzvPuuM75QdlSVUYtHsWjHIj649gOubHFl4QRpjDGFwPpAcmncOGjYEO66K+dj3/r1Ld5d9S6PX/A493a51//BGWNMIbIaSC6sXAn//S9MmABBQdkfu3DrQh5Z8gg3tr6RVy5/pXACNMaYQmQ1kFwYNw7q1oWhQ7M/LmJ/BLf85xbObXQu0/tOJ0DsYzbGlD5+/WYTkd4isk1EdorIaC/7m4rIdyKyXkRWiEiox74UEVnrvr7w2N5cRH51y5ztTpfrdz//DMuWweOPZz9F7Z9H/+S6z66jbpW6fDHwCyqX93E+W2OMKWH8lkBEJBB4F7gKaAMMEpE2mQ4bD0xX1Q7AWOBlj33xqhrmvvp4bP838KaqtgCOAIUyEuG4cc70tPdnM4HusYRjXPvZtcQnxfP1LV9Tr2q9wgjNGGOKhD9rIF2Bnaq6W1UTgVnA9ZmOaQN87y4v97I/A3EmCr8MmOtumgbcUGARZyEiAr75xplbumpV78ckpSRx8+c3s/XwVub1n0ebOplzpTHGlC7+TCCNgL0e65HuNk/rgH7ucl+gmojUcteDRCRCRH4RkbQkUQs4qqrJ2ZQJgIjc654fERUVla8LGTcOgoNh+HDv+1WV4YuGs3T3Uj649gN6ntUzX+9njDElQVH37j4GXCIia4BLgH1AiruvqTuM8C3ABBE5OzcFq+okVQ1X1fA6derkOcB16+CLL5zJoqpX937M+kPrmfz7ZB6/4HHu6uTD/b3GGFMK+PM23n1AY4/1UHdbOlXdj1sDEZGqwI2qetTdt8/9d7eIrAA6AfOAmiJSzq2FnFFmQfvnP53E8eCDWR+zL9YJoV/rflkfZIwxpYw/ayCrgJbuXVMVgIHAF54HiEhtkfR7XJ8CPna3B4tIxbRjgO7AZnVmv1oO3OSecwew0F8XsGkTzJ0LI0c6TVhZiY6LBqBWpVpZH2SMMaWM3xKIW0MYASwBtgBzVHWTiIwVkbS7qnoA20RkO1APeMnd3hqIEJF1OAnjFVXd7O57EnhERHbi9Il85K9reOklqFIFHn44++Ni4mMAbHIoY0yZ4tcn0VV1EbAo07bnPZbncvqOKs9jfgK8jjqoqrtx7vDyu6uvhm7dnNt3sxMTH4Mg1AyqWRhhGWNMsWBDmWTjttt8Oy46PpqaQTUJDPBxZiljjCkFivourFIhJj7Gmq+MMWWOJZACYAnEGFMWWQIpANHx0dSqbHdgGWPKFksgBcBqIMaYshU7llIAACAASURBVMgSSAGIiY8hJMgSiDGmbLEEkk/JqckcTThqTVjGmDLHEkg+HU04CthDhMaYsscSSD7ZU+jGmLLKEkg+2ThYxpiyyhJIPlkNxBhTVlkCyae0BGKd6MaYssYSSD5FxztNWFYDMcaUNZZA8iltJN4aFWsUdSjGGFOoLIHkU0x8DMGVgm0kXmNMmWMJJJ+i46Ot+coYUyb5NYGISG8R2SYiO0VktJf9TUXkOxFZLyIrRCTU3R4mIj+LyCZ33wCPc6aKyB8istZ9hfnzGnJi42AZY8oqvyUQEQkE3gWuAtoAg0SkTabDxgPTVbUDMBZ42d0eBwxW1bZAb2CCiHhO9/e4qoa5r7X+ugZfxMTH2DMgxpgyyZ81kK7ATlXdraqJwCzg+kzHtAG+d5eXp+1X1e2qusNd3g/8DdTxY6x5Fh1nTVjGmLLJnwmkEbDXYz3S3eZpHdDPXe4LVBORDH/Oi0hXoAKwy2PzS27T1psiUtHbm4vIvSISISIRUVFR+bmObFkTljGmrCrqTvTHgEtEZA1wCbAPSEnbKSINgBnAnaqa6m5+CjgHOBcIAZ70VrCqTlLVcFUNr1PHP5WX5NRkjp06Zk1YxpgyqZwfy94HNPZYD3W3pXObp/oBiEhV4EZVPequVwe+Bp5R1V88zjngLp4SkSk4SahIHIk/AthDhMaYssmfNZBVQEsRaS4iFYCBwBeeB4hIbRFJi+Ep4GN3ewVgPk4H+9xM5zRw/xXgBmCjH68hWzYOljGmLMsxgYjIdR5f8j5T1WRgBLAE2ALMUdVNIjJWRPq4h/UAtonIdqAe8JK7vT9wMTDEy+26M0VkA7ABqA38M7exFZS0YUxsHCxjTFnkSxPWAJzbaOcBH6vqVl8LV9VFwKJM2573WJ4LzPVy3ifAJ1mUeZmv7+9vVgMxxpRlOdYsVPU2oBPOXVBT3Qf87hWRan6PrpizBGKMKct8appS1eM4NYVZQAOcW25/F5GRfoyt2LPJpIwxZZkvfSB9RGQ+sAIoD3RV1auAjsCj/g2veEsfiTfIRuI1xpQ9vvSB3Ai8qaorPTeqapyI3O2fsEqGtJF4A3J/j4ExxpR4viSQMUDasxeISCWgnqruUdXv/BVYSRAdH23NV8aYMsuXP50/B1I91lPcbWWeDWNijCnLfEkg5dzBEAFwlyv4L6SSIyY+xp4BMcaUWb4kkCiPB/8QkeuBw/4LqeSwyaSMMWWZL30g9+M8/f0OIDgj7A72a1QlREx8DCFBlkCMMWVTjglEVXcB57mDHaKqJ/weVQmQlJLE8VPHrQnLGFNm+TQar4hcA7QFgpwxDEFVx/oxrmLvSIKNxGuMKdt8eZDwfZzxsEbiNGHdDDT1c1zFng1jYowp63zpRL9AVQcDR1T1ReB84B/+Dav4S0sg9hyIMaas8iWBJLj/xolIQyAJZzysMi1tHCyrgRhjyipf+kC+FJGawGvA74ACk/0aVQlgTVjGmLIu2wTiTiT1nTvN7DwR+QoIUtVjhRJdMZbehGV3YRljyqhsm7BUNRV412P9VG6Sh4j0FpFtIrJTREZ72d9URL4TkfUiskJEQj323SEiO9zXHR7bu4jIBrfMtyXttrBCFh0fTYAEUL1i9aJ4e2OMKXK+9IF8JyI35vaLWkQCcZLPVUAbYJCItMl02Hicec87AGOBl91zQ4AXgG5AV+AFEQl2z5kIDAVauq/euYmroMTExxAcZCPxGmPKLl++/e7DGTzxlIgcF5FYETnuw3ldgZ2qutsdP2sWcH2mY9oA37vLyz32XwksVdUYVT0CLAV6i0gDoLqq/qKqCkwHbvAhlgJn42AZY8o6X6a0raaqAapaQVWru+u+tNs0whn2JE2ku83TOqCfu9wXqCYitbI5t5G7nF2ZALjT7kaISERUVJQP4eaOjYNljCnrcrwLS0Qu9rY98wRTefQY8I6IDAFWAvtwhovPN1WdBEwCCA8P14Io01NMfAz1q9Yv6GKNMabE8OU23sc9loNwmqZWA5flcN4+oLHHeqi7LZ2q7setgbhjbd2oqkdFZB/QI9O5K9zzQzNtz1BmYYmJj6FtnbZF8dbGGFMs+NKEdZ3HqxfQDjjiQ9mrgJYi0lxEKgADgS88DxCR2u6twgBPAR+7y0uAK0Qk2O08vwJYoqoHgOMicp7bqT8YWOhDLAUuOs6asIwxZVtebiGKBFrndJCqJgMjcJLBFmCOqm4SkbEe84v0ALaJyHagHvCSe24MMA4nCa0CxrrbAIYBHwI7gV3AN3m4hnxJSkkiNjHWEogxpkzzpQ/k/3CePgcn4YThPJGeI1VdBCzKtO15j+W5wNwszv2Y0zUSz+0ROLWgIpM2Eq+Ng2WMKct86QOJ8FhOBj5T1R/9FE+JYONgGWOMbwlkLpCgqingPCAoIpVVNc6/oRVfNoyJMcb4+CQ6UMljvRKwzD/hlAzR8VYDMcYYXxJIkOc0tu5yZf+FVPzZSLzGGONbAjkpIp3TVkSkCxDvv5CKP5tMyhhjfOsDGQV8LiL7caa0rY8zxW2ZFR0XTaAE2ki8xpgyLccEoqqrROQcoJW7aZuqJvk3rOItJj6G4ErBFNFI8sYYUyzk2IQlIsOBKqq6UVU3AlVFZJj/Qyu+YhJirPnKGFPm+dIHMtSdkRAAd3j1of4LqfizYUyMMca3BBLoOZmUO1FUBf+FVPzFxMdYAjHGlHm+JJDFwGwR6SkiPYHPKILxp4oTm0zKGGN8uwvrSeBe4H53fT3OnVhlVnR8NCFBVgMxxpRtvgznngr8CuzBmQvkMpzRdcukxJRETiSesCYsY0yZl2UNRET+AQxyX4eB2QCqemnhhFY8HYl3R+K1JixjTBmXXRPWVuAH4FpV3QkgIg8XSlTFmI2DZYwxjuyasPoBB4DlIjLZ7UAv80/O2ThYxhjjyDKBqOoCVR0InAMsxxnSpK6ITBSRK3wpXER6i8g2EdkpIqO97G8iIstFZI2IrBeRq93tt4rIWo9XqoiEuftWuGWm7aublwvPKxsHyxhjHL50op9U1U9V9TogFFiDc2dWttznRd4FrgLaAINEpE2mw57Fmeq2E86c6e+57zlTVcNUNQy4HfhDVdd6nHdr2n5V/Tvnyyw4NpmUMcY4cjUnuqoeUdVJqtrTh8O7AjtVdbeqJgKzgOszFwmkjUhYA9jvpZxB7rnFgjVhGWOMI1cJJJcaAXs91iPdbZ7GALeJSCTO3OkjvZQzAOfhRU9T3Oar5zyfkvckIveKSISIRERFReXpAryJiY+xkXiNMQb/JhBfDAKmqmoocDUwQ0TSYxKRbkCcO4hjmltVtT1wkfu63VvBbk0pXFXD69SpU2ABR8c742DZSLzGmLLOnwlkH9DYYz3U3ebpbmAOgKr+DAQBtT32DyRT7UNV97n/xgKf4jSVFRobxsQYYxz+TCCrgJYi0lxEKuAkgy8yHfMX0BNARFrjJJAodz0A6I9H/4eIlBOR2u5yeeBaYCOFyAZSNMYYhy9jYeWJqiaLyAhgCRAIfKyqm0RkLBChql8AjwKT3QcUFRiiquoWcTGwV1V3exRbEVjiJo9AYBkw2V/X4E10fDSh1UML8y2NMaZY8lsCAVDVRTid457bnvdY3gx0z+LcFcB5mbadBLoUeKC5EBMfQ8d6HYsyBGOMKRaKuhO9xLEmLGOMcVgCyQUbidcYY06zBJILNoyJMcacZgkkF2wYE2OMOc0SSC7YMCbGGHOaJZBcSG/CsgcJjTHGEkhu2GRSxhhzmiWQXLAmLGOMOc0SSC7ExMdQLqAc1SpUK+pQjDGmyFkCyYXoOBuJ1xhj0lgCyYWYBHsK3Rhj0lgCyYWY+Bh7iNAYY1yWQHIhrQnLGGOMJZBcsYEUjTHmNEsguWBNWMYYc5olEB+dSj7FyaSTVgMxxhiXXxOIiPQWkW0islNERnvZ30RElovIGhFZLyJXu9ubiUi8iKx1X+97nNNFRDa4Zb4thXRPrT1EaIwxGfktgYhIIPAucBXQBhgkIm0yHfYsMEdVO+HMmf6ex75dqhrmvu732D4RGAq0dF+9/XUNnmwcLGOMycifNZCuwE5V3a2qicAs4PpMxyhQ3V2uAezPrkARaQBUV9Vf3LnTpwM3FGzY3tk4WMYYk5E/E0gjYK/HeqS7zdMY4DYRicSZO32kx77mbtPWf0XkIo8yI3MoEwARuVdEIkQkIioqKh+X4bDJpIwxJqOi7kQfBExV1VDgamCGiAQAB4AmbtPWI8CnIlI9m3LOoKqTVDVcVcPr1KmT70CtD8QYYzIq58ey9wGNPdZD3W2e7sbtw1DVn0UkCKitqn8Dp9ztq0VkF/AP9/zQHMr0C5uN0BhjMvJnDWQV0FJEmotIBZxO8i8yHfMX0BNARFoDQUCUiNRxO+ERkbNwOst3q+oB4LiInOfefTUYWOjHa0gXEx9D+YDyVK1QtTDezhhjij2/1UBUNVlERgBLgEDgY1XdJCJjgQhV/QJ4FJgsIg/jdKgPUVUVkYuBsSKSBKQC96tqjFv0MGAqUAn4xn35XdpT6DYSrzHGOPzZhIWqLsLpHPfc9rzH8magu5fz5gHzsigzAmhXsJHmLDrexsEyxhhPRd2JXmLExMfYMyDGGOPBEoiPbCBFY4zJyBKIj6wJyxhjMrIE4iMbidcYYzKyBOKDhOQE4pLirAZijDEeLIH4wJ5CN8aYM1kC8YGNg2WMMWeyBOIDG8bEGGPOZAnEB9aEZYwxZ7IE4gObTMoYY85kCcQHNpmUMcacyRKID9JG4q1SvkpRh2KMMcWGJRAfpI2DZSPxGmPMaZZAfGDDmBhjzJn8Opx7aWHDmJjSJCkpicjISBISEoo6FFNMBAUFERoaSvny5XN1niUQH8TEx9C8ZvOiDsOYAhEZGUm1atVo1qyZNcsaVJXo6GgiIyNp3jx333N+bcISkd4isk1EdorIaC/7m4jIchFZIyLrReRqd3svEVktIhvcfy/zOGeFW+Za91XXn9cAzoOE1oRlSouEhARq1bI+PeMQEWrVqpWnGqnfaiDunObvAr2ASGCViHzhzkKY5llgjqpOFJE2OLMXNgMOA9ep6n4RaYczLW4jj/NudWcmLBTWhGVKG0sexlNefx/8WQPpCuxU1d2qmgjMAq7PdIwC1d3lGsB+AFVdo6r73e2bgEoiUtGPsWYpPime+OR4q4EYY0wm/kwgjYC9HuuRZKxFAIwBbhORSJzax0gv5dwI/K6qpzy2TXGbr56TLFKniNwrIhEiEhEVFZXni7BhTIwpWNHR0YSFhREWFkb9+vVp1KhR+npiYmK250ZERPDggw/m+B4XXHBBQYVrslHUneiDgKmq+rqInA/MEJF2qpoKICJtgX8DV3icc6uq7hORasA84HZgeuaCVXUSMAkgPDxc8xqgDWNiTMGqVasWa9euBWDMmDFUrVqVxx57LH1/cnIy5cp5/2oKDw8nPDw8x/f46aefCibYQpSSkkJgYGBRh5Er/kwg+4DGHuuh7jZPdwO9AVT1ZxEJAmoDf4tIKDAfGKyqu9JOUNV97r+xIvIpTlPZGQmkoFgNxJRmoxaPYu3BtQVaZlj9MCb0npCrc4YMGUJQUBBr1qyhe/fuDBw4kIceeoiEhAQqVarElClTaNWqFStWrGD8+PF89dVXjBkzhr/++ovdu3fz119/MWrUqPTaSdWqVTlx4gQrVqxgzJgx1K5dm40bN9KlSxc++eQTRIRFixbxyCOPUKVKFbp3787u3bv56quvMsS1Z88ebr/9dk6ePAnAO++8k167+fe//80nn3xCQEAAV111Fa+88go7d+7k/vvvJyoqisDAQD7//HP27t2bHjPAiBEjCA8PZ8iQITRr1owBAwawdOlSnnjiCWJjY5k0aRKJiYm0aNGCGTNmULlyZQ4dOsT999/P7t27AZg4cSKLFy8mJCSEUaNGAfDMM89Qt25dHnroobz/8HLJnwlkFdBSRJrjJI6BwC2ZjvkL6AlMFZHWQBAQJSI1ga+B0ar6Y9rBIlIOqKmqh0WkPHAtsMyP12DjYBlTSCIjI/npp58IDAzk+PHj/PDDD5QrV45ly5bx9NNPM2/evDPO2bp1K8uXLyc2NpZWrVrxwAMPnPEsw5o1a9i0aRMNGzake/fu/Pjjj4SHh3PfffexcuVKmjdvzqBBg7zGVLduXZYuXUpQUBA7duxg0KBBRERE8M0337Bw4UJ+/fVXKleuTEyM84fmrbfeyujRo+nbty8JCQmkpqayd+9er2WnqVWrFr///jvgNO8NHToUgGeffZaPPvqIkSNH8uCDD3LJJZcwf/58UlJSOHHiBA0bNqRfv36MGjWK1NRUZs2axW+//Zbrzz0//JZAVDVZREbg3EEVCHysqptEZCwQoapfAI8Ck0XkYZwO9SGqqu55LYDnReR5t8grgJPAEjd5BOIkj8n+ugawyaRM6ZbbmoI/3XzzzelNOMeOHeOOO+5gx44diAhJSUlez7nmmmuoWLEiFStWpG7duhw6dIjQ0NAMx3Tt2jV9W1hYGHv27KFq1aqcddZZ6c89DBo0iEmTJp1RflJSEiNGjGDt2rUEBgayfft2AJYtW8add95J5cqVAQgJCSE2NpZ9+/bRt29fwHk4zxcDBgxIX964cSPPPvssR48e5cSJE1x55ZUAfP/990yf7jS0BAYGUqNGDWrUqEGtWrVYs2YNhw4dolOnTtSqVbjfU37tA1HVRTid457bnvdY3gx093LeP4F/ZlFsl4KMMSfWhGVM4ahS5fRgpc899xyXXnop8+fPZ8+ePfTo0cPrORUrnr45MzAwkOTk5Dwdk5U333yTevXqsW7dOlJTU31OCp7KlStHampq+nrm5y08r3vIkCEsWLCAjh07MnXqVFasWJFt2ffccw9Tp07l4MGD3HXXXbmOLb9sLKwcRMdFUyGwApXLVy7qUIwpM44dO0ajRs5Nm1OnTi3w8lu1asXu3bvZs2cPALNnz84yjgYNGhAQEMCMGTNISUkBoFevXkyZMoW4uDgAYmJiqFatGqGhoSxYsACAU6dOERcXR9OmTdm8eTOnTp3i6NGjfPfdd1nGFRsbS4MGDUhKSmLmzJnp23v27MnEiRMBp7P92LFjAPTt25fFixezatWq9NpKYbIEkoO0hwjtwStjCs8TTzzBU089RadOnXJVY/BVpUqVeO+99+jduzddunShWrVq1KhR44zjhg0bxrRp0+jYsSNbt25Nry307t2bPn36EB4eTlhYGOPHjwdgxowZvP3223To0IELLriAgwcP0rhxY/r370+7du3o378/nTp1yjKucePG0a1bN7p3784555yTvv2tt95i+fLltG/fni5durB5s/M8doUKFbj00kvp379/kdzBJap5vsO1xAgPD9eIiLw9uH7jnBvZdngbG4dtLOCojCkaW7ZsoXXr1kUdRpE7ceIEVatWRVUZPnw4LVu25OGHHy7qsHIlNTWVzp078/nnn9OyZct8leXt90JEVqtqlvdNWw0kBzYOljGl0+TJkwkLC6Nt27YcO3aM++67r6hDypXNmzfTokULevbsme/kkVdF/SBhsRcTH8PZIWcXdRjGmAL28MMPl7gah6c2bdqkPxdSVKwGkoPo+GhCgqwGYowxmVkCyUFMfIw1YRljjBeWQLIRnxRPQnKCjYNljDFeWALJhg1jYowxWbMEkg0bxsSY4qFq1aoA7N+/n5tuusnrMT169CCn2/UnTJiQ/vAfwNVXX83Ro0cLLtAyxhJINmwYE2OKl4YNGzJ37tw8n585gSxatIiaNWsWRGiFQlUzDItS1CyBZCM6zpqwTOk2ahT06FGwL3d08SyNHj2ad999N319zJgxjB8/nhMnTtCzZ086d+5M+/btWbhw4Rnn7tmzh3bt2gEQHx/PwIEDad26NX379iU+Pj79uAceeIDw8HDatm3LCy+8AMDbb7/N/v37ufTSS7n00ksBaNasGYcPHwbgjTfeoF27drRr144JEyakv1/r1q0ZOnQobdu25YorrsjwPmm+/PJLunXrRqdOnbj88ss5dOgQ4DyseOedd9K+fXs6dOiQPqLw4sWL6dy5Mx07dqRnz54ZPoc07dq1Y8+ePezZs4dWrVoxePBg2rVrx969e71eH8CqVau44IIL6NixI127diU2NpaLL744ff4VgAsvvJB169Zl/0PykT0Hkg2bTMqYgjdgwABGjRrF8OHDAZgzZw5LliwhKCiI+fPnU716dQ4fPsx5551Hnz59shxGaOLEiVSuXJktW7awfv16OnfunL7vpZdeIiQkhJSUFHr27Mn69et58MEHeeONN1i+fDm1a9fOUNbq1auZMmUKv/76K6pKt27duOSSSwgODmbHjh189tlnTJ48mf79+zNv3jxuu+22DOdfeOGF/PLLL4gIH374Ia+++iqvv/4648aNo0aNGmzYsAGAI0eOEBUVxdChQ9OHkk8bCj47O3bsYNq0aZx33nlZXt8555zDgAEDmD17Nueeey7Hjx+nUqVK3H333UydOpUJEyawfft2EhIS6Nixo+8/sGxYAsmGNWGZ0m5CEYzm3qlTJ/7++2/2799PVFQUwcHBNG7cmKSkJJ5++mlWrlxJQEAA+/bt49ChQ9SvX99rOStXrkyfQKpDhw506NAhfd+cOXOYNGkSycnJHDhwgM2bN2fYn9n//vc/+vbtmz7WVb9+/fjhhx/o06cPzZs3JywsDIAuXbqkD8DoKTIykgEDBnDgwAESExPTh4lftmwZs2bNSj8uODiYL7/8kosvvjj9mJCQnL9fmjZtmp48sro+EaFBgwace+65AFSvXh1whskfN24cr732Gh9//DFDhgzJ8f18ZQkkG9Hx0VQMrEilcpWKOhRjSpWbb76ZuXPncvDgwfT5MGbOnElUVBSrV6+mfPnyNGvW7Iyhz33xxx9/MH78eFatWkVwcDBDhgzJUzlpMg8H760Ja+TIkTzyyCP06dMnfRbE3Mpu2HfPId9ze32VK1emV69eLFy4kDlz5rB69epcx5YV6wPJRkx8DLUq20i8xhS0AQMGMGvWLObOncvNN98MOEOn161bl/Lly7N8+XL+/PPPbMu4+OKL+fTTTwFnIqb169cDcPz4capUqUKNGjU4dOgQ33zzTfo51apVIzY29oyyLrroIhYsWEBcXBwnT55k/vz5XHTRRT5fj+fw89OmTUvf3qtXrwz9PUeOHOG8885j5cqV/PHHHwDpTVjNmjVLn5nw999/T9+fWVbX16pVKw4cOMCqVasAZ2j4tJGM77nnHh588EHOPfdcgoODfb6unPg1gYhIbxHZJiI7RWS0l/1NRGS5iKwRkfUicrXHvqfc87aJyJW+llmQ7Cl0Y/yjbdu2xMbG0qhRIxo0aAA408FGRETQvn17pk+fnmE4c28eeOABTpw4QevWrXn++efp0sWZa65jx4506tSJc845h1tuuYXu3U/PWXfvvffSu3fv9E70NJ07d2bIkCF07dqVbt26cc8992Q77HpmY8aM4eabb6ZLly4Z+leeffZZjhw5Qrt27ejYsSPLly+nTp06TJo0iX79+tGxY8f0GtiNN95ITEwMbdu25Z133uEf//iH1/fK6voqVKjA7NmzGTlyJB07dqRXr17pNZMuXbpQvXp17rzzTp+vyRd+G85dRAKB7UAvIBJnjvRB7iyEacdMAtao6kQRaQMsUtVm7vJnQFegIc7UtWmfZrZlepPX4dxf/uFljp06xiuXv5Lrc40prmw497Jn//799OjRg61btxIQ4L3ekJfh3P3ZB9IV2Kmqu91AZgHXA55f9gpUd5drAPvd5euBWap6CvhDRHa65eFDmQXmqYue8kexxhhTaKZPn84zzzzDG2+8kWXyyCt/JpBGwF6P9UigW6ZjxgDfishIoApwuce5v2Q6t5G7nFOZAIjIvcC9AE2aNMl99MYYUwoMHjyYwYMH+6Xsou5EHwRMVdVQ4GpghogUSEyqOklVw1U1vE6dOgVRpDGlRlmYidT4Lq+/D/5MIPuAxh7roe42T3cDcwBU9WcgCKidzbm+lGmMyUZQUBDR0dGWRAzgJI/o6GiCgoJyfa4/m7BWAS1FpDnOl/xA4JZMx/wF9ASmikhrnAQSBXwBfCoib+B0orcEfgPEhzKNMdkIDQ0lMjKSqKioog7FFBNBQUGEhobm+jy/JRBVTRaREcASIBD4WFU3ichYIEJVvwAeBSaLyMM4HepD1PmzaJOIzMHpHE8GhqtqCoC3Mv11DcaURuXLl09/CtqY/PDbbbzFSV5v4zXGmLIsp9t4i7oT3RhjTAllCcQYY0yelIkmLBGJArIfWCdrtYHDBRhOcVDarsmup/grbddU2q4HvF9TU1XN8jmIMpFA8kNEIrJrAyyJSts12fUUf6Xtmkrb9UDersmasIwxxuSJJRBjjDF5YgkkZ5OKOgA/KG3XZNdT/JW2aypt1wN5uCbrAzHGGJMnVgMxxhiTJ5ZAjDHG5IklkGwU5vS5hUFE9ojIBhFZKyIlcmwXEflYRP4WkY0e20JEZKmI7HD/LbhJn/0si+sZIyL73J/TWs+pnos7EWnsTlO9WUQ2ichD7vaS/DPK6ppK5M9JRIJE5DcRWedez4vu9uYi8qv7fTdbRCrkWJb1gXjny5S8JY2I7AHCVbXEPgAlIhcDJ4DpqtrO3fYqEKOqr7iJPlhVnyzKOH2VxfWMAU6o6viijC0vRKQB0EBVfxeRasBq4AZgCCX3Z5TVNfWnBP6cRESAKqp6QkTKA/8DHgIeAf6jqrNE5H1gnapOzK4sq4FkLX1KXlVNBNKmzzVFSFVXAjGZNl8PTHOXp+H85y4RsrieEktVD6jq7+5yLLAFZzbRkvwzyuqaSiR1nHBXy7svBS4D5rrbffoZWQLJmrcpeUvsL41LcaYQXu1O+Vta1FPVA+7yQaBeUQZTQEaIyHq3iavE1yW9ogAAA81JREFUNPd4EpFmQCfgV0rJzyjTNUEJ/TmJSKCIrAX+BpYCu4CjqprsHuLT950lkLLlQlXtDFwFDHebT0oVdz6Zkt4uOxE4GwgDDgCvF204uSciVYF5wChVPe65r6T+jLxcU4n9OalqiqqG4czq2hU4Jy/lWALJWqmbPldV97n//g3Mx/nFKQ0Oue3Uae3VfxdxPPmi/9/eHYPWVcVxHP/+mjqECG1txaWGUOxUWqm4WDoUhy5OYrEGhSIO2kGdJOIiiF06SInNYpFSMBoC1egUWtIiBQU7VKuSrXTT0gwpFKSU5O9w/mkvmpfG07wkF3+fJTfnvVzu4ZD7f+ec+/7/iBv5Dz4PnKJl45Tr6meB0Yj4OptbPUaL9ant4wQQEbPAReA5YLOkhSKDy7rfOYB0dq8kbz6N8Aql1G4rSerLDUAk9QEHgd+W/qvW+A44ksdHgG/X8Foe2sKNNr1Ii8YpN2g/B6Yj4pPGS60do059aus4SXpc0uY87qU8KDRNCSSH8m3LGiM/hbWEfCzvBPfL5x5b40uqJmkHZdYBpZTxl23sj6SvgAOU1NM3gA+BCWAc6Kek7X85IlqxMd2hPwcoyyIBXAfebOwfrGuS9gOXgF+B+Wz+gLJn0NYx6tSnQVo4TpL2UDbJeyiTiPGI+CjvEWPAY8AV4LWIuLPkuRxAzMyshpewzMysigOImZlVcQAxM7MqDiBmZlbFAcTMzKo4gJhVkjTXyMT680pmbJY00MzQa7YebXzwW8ysg78yHYTZ/5JnIGYrLOuuHM/aKz9JeirbByRdyOR7U5L6s/0JSd9kfYZfJO3LU/VIOpU1G87lt4aR9E7WprgqaWyNumnmAGL2EHr/sYR1uPHarYjYDZykZDMA+BQ4ExF7gFFgONuHge8j4mngGeD3bN8JjETELmAWeCnb3wf25nne6lbnzB7E30Q3qyTpdkQ8ukj7deD5iLiWSfj+jIitkmYohYnuZvsfEbFN0k1gezNtRKYNPx8RO/P3IeCRiPhY0iSlCNUEMNGo7WC2qjwDMeuO6HD8XzTzEM1xf8/yBWCEMlu53MigaraqHEDMuuNw4+ePefwDJaszwKuUBH0AU8BRuFfoZ1Onk0raADwZEReBIWAT8K9ZkNlq8CcXs3q9WdVtwWRELDzKu0XSVcosYjDb3gZOS3oPuAm8nu3vAp9JeoMy0zhKKVC0mB7giwwyAoazpoPZqvMeiNkKyz2QZyNiZq2vxaybvIRlZmZVPAMxM7MqnoGYmVkVBxAzM6viAGJmZlUcQMzMrIoDiJmZVfkbcUWlYXT0p4cAAAAASUVORK5CYII=\n",
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "tags": [],
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "PVkSCyqGlwTE",
        "outputId": "5c19888b-3c19-4baf-8cb6-390f74b9fbd0",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 295
        }
      },
      "source": [
        "beginner.loss_vs_valloss(model,history,30)"
      ],
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYMAAAEWCAYAAACEz/viAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3dd3hUZfbA8e/JpJFCTVR6EZQaKQELiqCuioqiwgKLAnZcXRQXe0N3da0sq+Lu4k+xi6wIgqLYULDRBFREFJESmtSQkISUOb8/7k0Y0ttkSO75PM88uf2eOwNz5n3fe99XVBVjjDHeFhbqAIwxxoSeJQNjjDGWDIwxxlgyMMYYgyUDY4wxWDIwxhiDJQNTzUTkfREZXd3bhpKIbBCRs4Jw3M9E5Gp3eqSIfFiebStxnlYiki4ivsrGWsqxVUTaV/dxTc2zZGBwvyjyX34RyQyYH1mRY6nqQFV9qbq3PRKJyB0isrCY5Qkiki0iXct7LFV9TVXPrqa4DkteqrpJVeNUNa86jm/qJksGBveLIk5V44BNwKCAZa/lbyci4aGL8oj0KnCKiLQttHw48L2q/hCCmIypFEsGpkQi0l9EUkTkdhHZDkwTkUYi8q6I7BSRve50i4B9Aqs+xojIFyLyhLvtbyIysJLbthWRhSKSJiIfi8gUEXm1hLjLE+PfRORL93gfikhCwPrLRWSjiOwWkbtLen9UNQX4FLi80KpRwMtlxVEo5jEi8kXA/B9E5CcRSRWRZwAJWHesiHzqxrdLRF4TkYbuuleAVsBct2R3m4i0catzwt1tmonIHBHZIyLrROSagGNPFJEZIvKy+96sFpHkkt6DQtfQwN1vp/v+3SMiYe669iLyuXs9u0TkTXe5iMg/ReR3EdkvIt9XpERlqo8lA1OWY4DGQGvgWpx/M9Pc+VZAJvBMKfufCKwFEoDHgOdFRCqx7evAEqAJMJGiX8CByhPjn4ArgKOASGACgIh0Bv7tHr+Ze75iv8BdLwXGIiLHA93deCv6XuUfIwF4G7gH5734FegbuAnwDze+TkBLnPcEVb2cw0t3jxVziulAirv/EOBhETkjYP2F7jYNgTnlidn1NNAAaAecjpMUr3DX/Q34EGiE834+7S4/G+gHHOfu+0dgdznPZ6qTqtrLXgUvYANwljvdH8gGokvZvjuwN2D+M+Bqd3oMsC5gXQygwDEV2RbnizQXiAlY/yrwajmvqbgY7wmY/zPwgTt9HzA9YF2s+x6cVcKxY4D9wCnu/EPAO5V8r75wp0cB3wRsJzhf3leXcNzBwIriPkN3vo37XobjJI48ID5g/T+AF93picDHAes6A5mlvLcKtAd87vvUOWDddcBn7vTLwFSgRaH9zwB+Bk4CwkL979/LLysZmLLsVNWs/BkRiRGR/7rVAPuBhUBDKflOle35E6qa4U7GVXDbZsCegGUAm0sKuJwxbg+YzgiIqVngsVX1AKX8UnVj+h8wyi3FjMT54qvMe5WvcAwaOC8iR4vIdBHZ4h73VZwSRHnkv5dpAcs2As0D5gu/N9FSdntRAhDhHqu4496Gk9SWuFVPV7rX9ilOyWMK8LuITBWR+uW8FlONLBmYshTu1vavwPHAiapaH6eIDwF12kGwDWgsIjEBy1qWsn1VYtwWeGz3nE3K2OclnOqNPwDxwNwqxlE4BuHw630Y53Pp5h73skLHLK0r4q0472V8wLJWwJYyYirLLiAHp0qsyHFVdbuqXqOqzXBKDM+Ke0uqqj6lqr1wSiHHAbdWMRZTCZYMTEXF49R97xORxsD9wT6hqm4ElgETRSRSRE4GBgUpxreAC0TkVBGJBB6k7P8ni4B9ONUg01U1u4pxvAd0EZFL3F/k43Cqy/LFA+lAqog0p+iX5w6cevsiVHUz8BXwDxGJFpEk4Cqc0kWlqXPb6gzgIRGJF5HWwC35xxWRoQGN53txEpZfRHqLyIkiEgEcALIAf1ViMZVjycBU1GSgHs4vwW+AD2rovCOBk3GqbP4OvAkcLGHbSseoqquBG3AagLfhfHGllLGP4lQNtXb/VikOVd0FDAUewbneDsCXAZs8APQEUnESx9uFDvEP4B4R2SciE4o5xQicdoStwCzgflX9uDyxleEvOF/o64EvcN7DF9x1vYHFIpKO0yh9k6quB+oDz+G8zxtxrvfxaojFVJC4jTjG1CrurYk/qWrQSybGeIGVDEyt4FYnHCsiYSJyLnARMDvUcRlTV9gTpaa2OAanOqQJTrXN9aq6IrQhGVN3WDWRMcYYqyYyxhhTC6uJEhIStE2bNqEOwxhjapXly5fvUtXEktbXumTQpk0bli1bFuowjDGmVhGRjaWtt2oiY4wxlgyMMcZYMjDGGEMtbDMwxtS8nJwcUlJSyMrKKntjE1LR0dG0aNGCiIiICu1nycAYU6aUlBTi4+Np06YNJY9NZEJNVdm9ezcpKSm0bVt4NNbSWTWRMaZMWVlZNGnSxBLBEU5EaNKkSaVKcJYMjDHlYomgdqjs5+SZZPDFpi+48+M7se43jDGmKM8kg6VblvLIl4+wL2tfqEMxxlTQ7t276d69O927d+eYY46hefPmBfPZ2dml7rts2TLGjRtX5jlOOeWUaon1s88+44ILLqiWY9UkzzQgJ8Q4Q8TuythFo3qNQhyNMaYimjRpwsqVKwGYOHEicXFxTJhwaNye3NxcwsOL/zpLTk4mOTm5zHN89dVX1RNsLeWZkkFirNMlx86MnSGOxBhTHcaMGcPYsWM58cQTue2221iyZAknn3wyPXr04JRTTmHt2rXA4b/UJ06cyJVXXkn//v1p164dTz31VMHx4uLiCrbv378/Q4YMoWPHjowcObKgennevHl07NiRXr16MW7cuDJLAHv27GHw4MEkJSVx0kkn8d133wHw+eefF5RsevToQVpaGtu2baNfv350796drl27smjRomp/z0rjyZKBMabybv7gZlZuX1mtx+x+THcmnzu5wvulpKTw1Vdf4fP52L9/P4sWLSI8PJyPP/6Yu+66i5kzZxbZ56effmLBggWkpaVx/PHHc/311xe5J3/FihWsXr2aZs2a0bdvX7788kuSk5O57rrrWLhwIW3btmXEiBFlxnf//ffTo0cPZs+ezaeffsqoUaNYuXIlTzzxBFOmTKFv376kp6cTHR3N1KlTOeecc7j77rvJy8sjIyOjwu9HVXgmGSTGuCWDA1YyMKauGDp0KD6fD4DU1FRGjx7NL7/8goiQk5NT7D7nn38+UVFRREVFcdRRR7Fjxw5atGhx2DZ9+vQpWNa9e3c2bNhAXFwc7dq1K7h/f8SIEUydOrXU+L744ouChHTGGWewe/du9u/fT9++fbnlllsYOXIkl1xyCS1atKB3795ceeWV5OTkMHjwYLp3716l96aiPJMMrGRgTPWozC/4YImNjS2YvvfeexkwYACzZs1iw4YN9O/fv9h9oqKiCqZ9Ph+5ubmV2qYq7rjjDs4//3zmzZtH3759mT9/Pv369WPhwoW89957jBkzhltuuYVRo0ZV63lL45k2g9jIWOqF17M2A2PqqNTUVJo3bw7Aiy++WO3HP/7441m/fj0bNmwA4M033yxzn9NOO43XXnsNcNoiEhISqF+/Pr/++ivdunXj9ttvp3fv3vz0009s3LiRo48+mmuuuYarr76ab7/9ttqvoTSeSQbglA6sZGBM3XTbbbdx55130qNHj2r/JQ9Qr149nn32Wc4991x69epFfHw8DRo0KHWfiRMnsnz5cpKSkrjjjjt46aWXAJg8eTJdu3YlKSmJiIgIBg4cyGeffcYJJ5xAjx49ePPNN7npppuq/RpKU+vGQE5OTtbKDm7Ta2ovjok7hvf+9F41R2VM3bZmzRo6deoU6jBCLj09nbi4OFSVG264gQ4dOjB+/PhQh1VEcZ+XiCxX1RLvsQ1qyUBEzhWRtSKyTkTuKGW7S0VERaTsm4GrwEoGxpiqeO655+jevTtdunQhNTWV6667LtQhVZugNSCLiA+YAvwBSAGWisgcVf2x0HbxwE3A4mDFki8xJpFfdv8S7NMYY+qo8ePHH5ElgeoQzJJBH2Cdqq5X1WxgOnBRMdv9DXgUCHpH6VYyMMaY4gUzGTQHNgfMp7jLCohIT6ClqpZaiS8i14rIMhFZtnNn5e8GSoxJJC07jYO5Byt9DGOMqYtCdjeRiIQBk4C/lrWtqk5V1WRVTU5MTKz0Oe1ZA2OMKV4wk8EWoGXAfAt3Wb54oCvwmYhsAE4C5gSzEdn6JzLGmOIFMxksBTqISFsRiQSGA3PyV6pqqqomqGobVW0DfANcqKqVu2+0HKxkYIx35Hc8t3XrVoYMGVLsNv3796esW9UnT558WD9B5513Hvv2Vb0r/IkTJ/LEE09U+TjVJWjJQFVzgRuB+cAaYIaqrhaRB0XkwmCdtzTWP5Ex3tOsWTPeeuutSu9fOBnMmzePhg0bVkdoR5Sgthmo6jxVPU5Vj1XVh9xl96nqnGK27R/MUgFYycCY2uqOO+5gypQpBfP5v6rT09M588wz6dmzJ926deOdd94psu+GDRvo2rUrAJmZmQwfPpxOnTpx8cUXk5mZWbDd9ddfT3JyMl26dOH+++8H4KmnnmLr1q0MGDCAAQMGANCmTRt27XK+QyZNmkTXrl3p2rUrkydPLjhfp06duOaaa+jSpQtnn332YecpzsqVKznppJNISkri4osvZu/evQXn79y5M0lJSQwfPhwovvvr6uCZjuoAGtdrjCDWZmBMFdx8M6ys3h6s6d4dJpfS/92wYcO4+eabueGGGwCYMWMG8+fPJzo6mlmzZlG/fn127drFSSedxIUXXljiOMD//ve/iYmJYc2aNXz33Xf07NmzYN1DDz1E48aNycvL48wzz+S7775j3LhxTJo0iQULFpCQkHDYsZYvX860adNYvHgxqsqJJ57I6aefTqNGjfjll1944403eO655/jjH//IzJkzueyyy0q8vlGjRvH0009z+umnc9999/HAAw8wefJkHnnkEX777TeioqIKqqaK6/66OniqbyJfmI/G9RpbNZExtUyPHj34/fff2bp1K6tWraJRo0a0bNkSVeWuu+4iKSmJs846iy1btrBjx44Sj7Nw4cKCL+WkpCSSkpIK1s2YMYOePXvSo0cPVq9ezY8//ljSYQCne+qLL76Y2NhY4uLiuOSSSwoGpGnbtm1BF9S9evUq6NyuOKmpqezbt4/TTz8dgNGjR7Nw4cKCGEeOHMmrr75aMJJbfvfXTz31FPv27StxhLeK8lTJAJw7inZlWjWRMZVV2i/4YBo6dChvvfUW27dvZ9iwYQC89tpr7Ny5k+XLlxMREUGbNm3Iyqr486u//fYbTzzxBEuXLqVRo0aMGTOmUsfJV7gL7LKqiUry3nvvsXDhQubOnctDDz3E999/X2z31x07dqx0rPk8VTIApxHZSgbG1D7Dhg1j+vTpvPXWWwwdOhRwflUfddRRREREsGDBAjZu3FjqMfr168frr78OwA8//FAwDOX+/fuJjY2lQYMG7Nixg/fff79gn/j4+GLr5U877TRmz55NRkYGBw4cYNasWZx22mkVvq4GDRrQqFGjglLFK6+8wumnn47f72fz5s0MGDCARx99lNTUVNLT04vt/ro6eK5kkBCTwM+7fw51GMaYCurSpQtpaWk0b96cpk2bAjBy5EgGDRpEt27dSE5OLvMX8vXXX88VV1xBp06d6NSpE7169QIo6Dq6Y8eOtGzZkr59+xbsc+2113LuuefSrFkzFixYULC8Z8+ejBkzhj59+gBw9dVX06NHj1KrhEry0ksvMXbsWDIyMmjXrh3Tpk0jLy+Pyy67jNTUVFSVcePG0bBhQ+69914WLFhAWFgYXbp0YeDAgRU+X3E81YU1wHVzr2P22tnsmFByvaIx5nDWhXXtcsR1YX0kSohJYHfGbvzqD3UoxhhzxPBcMkiMTSRP89iXVfUnCI0xpq7wXDKwB8+MqZzaVqXsVZX9nDyXDKxLCmMqLjo6mt27d1tCOMKpKrt3767Ug2ievJsIrGRgTEW0aNGClJQUqjKeiKkZ0dHRtGjRosL7eS4ZWDfWxlRcREQEbdu2DXUYJog8V01kJQNjjCnKc8kgJiKGmIgYazMwxpgAnksG4JQOrH8iY4w5xJPJwPonMsaYw3kyGSTEJFibgTHGBPBkMkiMTbS7iYwxJoAnk0FCPSsZGGNMIE8mg8TYRNKz08nKrfzgFcYYU5d4MhnYswbGGHM4TyYD65/IGGMO58lkkF8ysEZkY4xxeDIZ5PdPZNVExhjj8GQyKCgZWDWRMcYAHk0GjaIbESZhVjIwxhiXJ5OBL8xH43qNrc3AGGNcnkwG4NxRZCUDY4xxeDYZJMQkWMnAGGNcnk0GibFWMjDGmHyeTQYJ9RLsbiJjjHF5NhkkxiayO3M3fvWHOhRjjAk57yaDmET86mdv5t5Qh2KMMSHn2WRgndUZY8whnk0G+V1S2B1Fxhjj4WRgJQNjjDnEs8nAurE2xphDgpoMRORcEVkrIutE5I5i1o8Vke9FZKWIfCEinYMZTyArGRhjzCFBSwYi4gOmAAOBzsCIYr7sX1fVbqraHXgMmBSseAqrF1GP2IhYazMwxhiCWzLoA6xT1fWqmg1MBy4K3EBV9wfMxgIaxHiKSIhJsJKBMcYA4UE8dnNgc8B8CnBi4Y1E5AbgFiASOCOI8RSRGJtoJQNjjOEIaEBW1SmqeixwO3BPcduIyLUiskxElu3cWX1f3lYyMMYYRzCTwRagZcB8C3dZSaYDg4tboapTVTVZVZMTExOrLcDEmES7m8gYYwhuMlgKdBCRtiISCQwH5gRuICIdAmbPB34JYjxFWDfWxhjjCFqbgarmisiNwHzAB7ygqqtF5EFgmarOAW4UkbOAHGAvMDpY8RQnMSaRjJwMMnIyiImIqclTG2PMESWYDcio6jxgXqFl9wVM3xTM85cl8FmDVg1ahTIUY4wJqZA3IIdSfv9E1ohsjPE6TyeD/JKBNSIbY7zO08kgv38iKxkYY7zO08mgoGRgdxQZYzzO08mgUb1GhEmYlQyMMZ7n6WQQJmE0qdfE2gyMMZ7n6WQAzh1FuzKtZGCM8TbPJ4OEmAQrGRhjPM/zySAxJtHaDIwxnuf5ZGD9ExljjCUDEmMS2ZO5hzx/XqhDMcaYkPF8MkiIScCvfvZm7Q11KMYYEzKeTwbWP5ExxlgysP6JjDEGSwbWP5ExxmDJoKCayO4oMsZ4meeTQeAAN8YY41WeTwbR4dHERcZZm4ExxtM8nwzAHjwzxhhLBliXFMYYY8kAKxkYY4wlA9xurK1kYIzxMEsGQEI968baGONtlgxwSgaZuZlk5GSEOhRjjAkJSwZYlxTGGGPJAOuSwhhjLBkQUDKwO4qMMR5VrmQgIrEiEuZOHyciF4pIRHBDqznWjbUxxuvKWzJYCESLSHPgQ+By4MVgBVXTrM3AGON15U0GoqoZwCXAs6o6FOgSvLBqVsPohvjEZyUDY4xnlTsZiMjJwEjgPXeZLzgh1bwwCaNJTBNrMzDGeFZ5k8HNwJ3ALFVdLSLtgAXBC6vmWf9ExhgvCy/PRqr6OfA5gNuQvEtVxwUzsJpm/RMZY7ysvHcTvS4i9UUkFvgB+FFEbg1uaDXL+icyxnhZeauJOqvqfmAw8D7QFueOojrD+icyxnhZeZNBhPtcwWBgjqrmABq8sGpeYmwiezL3kOfPC3UoxhhT48qbDP4LbABigYUi0hrYH6ygQiEhJgFF2ZO5J9ShGGNMjStXMlDVp1S1uaqep46NwIAgx1ajrH8iY4yXlbcBuYGITBKRZe7rSZxSQln7nSsia0VknYjcUcz6W0TkRxH5TkQ+cUscIWH9ExljvKy81UQvAGnAH93XfmBaaTuIiA+YAgwEOgMjRKRzoc1WAMmqmgS8BTxW/tCrV37/RNaIbIzxonI9ZwAcq6qXBsw/ICIry9inD7BOVdcDiMh04CLgx/wNVDXwwbVvgMvKGU+1yy8ZWDWRMcaLylsyyBSRU/NnRKQvkFnGPs2BzQHzKe6yklyFc9tqESJybX4V1c6dwfnlnt9mYNVExhgvKm8yGAtMEZENIrIBeAa4rrqCEJHLgGTg8eLWq+pUVU1W1eTExMRKnWPWLBg0CLSEG2KjwqOIj4y3koExxpPKezfRKlU9AUgCklS1B3BGGbttAVoGzLdwlx1GRM4C7gYuVNWD5Yq6EvbuhXffhXXrSt7GuqQwxnhVhUY6U9X97pPIALeUsflSoIOItBWRSGA4MCdwAxHpgfMMw4Wq+ntFYqmoPn2cv0uWlLyNdUlhjPGqqgx7KaWtVNVc4EZgPrAGmOH2ePqgiFzobvY4EAf8T0RWisicEg5XZZ06QWxs6ckgIca6pDDGeFN57yYqTpndUajqPGBeoWX3BUyfVYXzV4jPB716lVEyiEnk+x3f11RIxhhzxCi1ZCAiaSKyv5hXGtCshmKsNn36wIoVkJ1d/Pr8NgMtqZXZGGPqqFKTgarGq2r9Yl7xqlqVUkVI9OkDBw/C9yX8+E+MSSQrN4uMnIyaDcwYY0KsKm0GtU5ZjcjWJYUxxqs8lQxatYKjjio5GeR3SWF3FBljvMZTyUDEKR2UWTKwO4qMMR7jqWQATjJYswbS0oqus26sjTFe5blk0Lu30yXF8uVF11mbgTHGqzyZDKD4qqKG0Q3xic9KBsYYz/FcMmjSBI49tvhkICL2FLIxxpM8lwyg9EbkxNhEdmVaycAY4y2eTQabN8O2bUXXWcnAGONFnk0GAEuXFl2XGGM9lxpjvMeTyaBHD6fjuuKqimxMA2OMF3kyGdSrB0lJJZcM9mTuIdefW/OBGWNMiHgyGYBzi+mSJUWHwcx/1mBP5p4QRGWMMaHh2WTQpw/s21d0GMz8/omsEdkY4yWeTgZQtN0gv2RgjcjGGC/xbDLo3Ln4YTDz+yeyRmRjjJd4NhmUNAymlQyMMV7k2WQAxQ+Dad1YG2O8yPPJoPAwmFHhUbRt2JaP1n8UusCMMaaGeT4ZQNGqor/0+QuLNi1iccrimg/KGGNCwNPJoFUrSEws+vDZ1T2vpkFUA574+onQBGaMMTXM08mgpGEw46PiGZs8lrfXvM2ve34NTXDGGFODPJ0MwEkGP/5YdBjMcSeOwyc+/vnNP0MTmDHG1CBLBn2KHwazWXwzRiaN5IUVL7A7Y3dogjPGmBri+WRQ2jCYE06eQGZuJs8ufbZmgzLGmBrm+WRQ2jCYXY7qwnkdzuPpJU+TlZtV88EZY0wN8XwygNKHwZxw8gR2Zuzk5VUv12xQxhhTgywZ4FQVbd4M27cXXde/TX96Ne3Fk18/iV/9NR+cMcbUAEsGlD4Mpogw4ZQJ/Lz7Z+aunVuzgRljTA2xZEDpw2ACDOk8hNYNWttDaMaYOsuSARATA926lZwMwsPCGX/SeL7Y9AXfpHxTs8EZY0wNsGTgym9ELjwMZr6rel5Fw+iGPP7V4zUbmDHG1ABLBq6ShsHMFxcZx/XJ1zNrzSzW7SlhI2OMqaUsGbhK6sE00F/6/IUIXwSTvp5UM0EZY0wNsWTgKmkYzEBN45tyWbfLmLZymg1+Y4ypU4KaDETkXBFZKyLrROSOYtb3E5FvRSRXRIYEM5ay+HzQs2fpyQBgwikTyMrNsi4qjDF1StCSgYj4gCnAQKAzMEJEOhfabBMwBng9WHFURP4wmDk5JW/TKbETFxx3Ac8sfYbMnMyaC84YY4IomCWDPsA6VV2vqtnAdOCiwA1UdYOqfgccEY/2FjcMZnEmnDyBXRm7eGnVSzUTmDHGBFkwk0FzYHPAfIq77IhVnkZkgH6t+9G7WW8mfT2JPH9e8AMzxpggqxUNyCJyrYgsE5FlO3cGr+G2dWtnGMyykkF+FxW/7PmFOWvnBC0eY4ypKcFMBluAlgHzLdxlFaaqU1U1WVWTExMTqyW44pQ0DGZxLul0CW0btuWxrx5DS3pSzRhjaolgJoOlQAcRaSsikcBw4Ij/GV3SMJiFhYeFc8epd/BNyjc8tOihmgnOGGOCJGjJQFVzgRuB+cAaYIaqrhaRB0XkQgAR6S0iKcBQ4L8isjpY8ZRXScNgFueantdwedLl3LvgXmasnhH84IwxJkjCg3lwVZ0HzCu07L6A6aU41UdHjORk5++nn0L//qVvKyI8N+g51u9dz+jZo2nTsA19mvcJeozGGFPdakUDck1KSIBBg+CRR+CLL8rePio8ilnDZtE0rikXvnEhm1I3BT9IY4ypZpYMivHyy9CmDVx6qTMCWlkSYxN590/vkpmbyaA3BpF2sIwGB2OMOcJYMihGw4YwZw5kZcHgwZCRUfY+nRM787+h/2P176v509t/sucPjDG1iiWDEnTsCK+/7nRPcfXVJY9zEOjsY8/m6YFP8+7P73LbR7cFP0hjjKkmlgxKcf758PDD8MYb8Hg5x7S5vvf1jOszjknfTGLq8qnBDdB40vvvw+7doY7C1DWWDMpw++0wbBjccQfMm1f29gBPnvMkA9sP5IZ5N/DJ+k+CG6DxlIUL4bzz4N57Qx2JqWssGZRBBF54Abp3hxEjYO3asvcJDwtn+pDpdEzoyJD/DWHtrnLsZEwZVGHCBGf6tdfgwIHQxmPqFksG5RATA7NnQ1QUXHihMzxmWepH1WfuiLlE+OM59c+v0rFzLuPHl949tjGl+d//YOlSuPJK2L8f3nor1BGZusSSQTm1agUzZ8L69TByJOSVcbNQejrMfL4NOnkdu/73Nzbt3crkyXDWWfD77zUTs6k7Dh6EO++Ebt1g6lQ4/nh47rlQR2XqEksGFXDaafDMM07bwd13F7/N3r3w4INOD6gTJkBS10jufu5TMq9rTb/xU1m6VOnVC5Ytq9nYTe32n/84P0Qee8wZle/qq+HLL51+tIypFqpaq169evXSUBs7VhVUX3/90LLt21Vvu001Ls5ZN2iQ6tdfH1p//4L7lYnoTS+8qK1bq0ZFqU6bVtORm9po717VJk1UzzpL1e93lu3YoRoRoXrLLaGNzdQewDIt5bs15F/uFX0dCcng4EHVfv1Uo6NV33lH9YYbnOmwMNXhwwm/2BkAABcZSURBVFVXrSq6j9/v12H/G6YyUfSVr9/XM8903v0bb1TNzq75azC1x+23O/9Wvv328OVDhjhJIisrNHGZ2sWSQZDs2KHaqpXzDkZEqF51lerPP5e+T0Z2hvZ5ro/GPhSrSzev0L/+1dn/tNOckoUxhW3c6JQiL7us6Lr5851/P9On13xcpvYpKxmIs03tkZycrMuOkAr3H3907vC48kpo2bLs7QG2pW2jz/85PZsuuXoJn73blKuugsaN4e23Dw29aQzAmDEwfbpzS3Pr1oev8/uhXTvo0AE++igk4ZlaRESWq2pySeutAbkKOneG++8vfyIAaBrflLkj5rI3cy+D3xzM4CGZfPUVREQ4DdQvvBC8eE3tsmqV02niuHFFEwFAWBhcdRV8/LHTuGxMVVgyCIHux3TntUteY+mWpVzxzhWccIKybBn06+f8577hBsjNDXWUJtRuu83pNPHOO0ve5oornKTw/PM1F5epmywZhMhFHS/ikbMe4c3Vb/LA5w/QpInT58yECfDss05vqfaEqXd9+KHzuuceaNSo5O1atHC6p5g2zX5AmKqxZBBCt55yK1d0v4IHPn+A6T9MJzzc6RDvP/9xEkP//vaAmhf5/U6poE0bp5RYlquvhm3byt93ljHFsWQQQiLCfy74D6e1Oo0xs8ewOGUxANdd53R/sXo1nHwy/PJLiAM1NerVV532gocfdrpAKcv550PTpvZEsqkaSwYhFumL5O1hb9O8fnMumn5RwbCZgwbBggVOHzSnnAKLF4c4UFMjMjOdqqFevZzecssjPNxpO5g3D1JSghufqbssGRwBEmISmDtibpFhM088Eb76Cho0gAEDnNHXTN329NPOUKuPP+40DJfXlVc61Usvvhi00EwdZ88ZHEHmr5vP+a+fz8ktT+a89ufRLL4ZzeKbEX2wFTePOpaVK3xMmSKMHRvqSE0w7N4Nxx4Lp54K775b8f3POgt+/dV5hYVBRk4G29O3065Ru+oP1tQ6ZT1nYMngCPP8t89z28e3sSdzz+ErsmMIm/kW/rUDaXnBK5wyeh7N4psSERZBdl42B/MOkp2XXXQ615luGN2QscljGdh+ICJSo9e0Zo3TGFqvXo2ettYZPx6eesppL+jateL7v/kmDB8O8+fDqQMyGPDSAFZtX8XKsSvpmNCx+gM2tYolg1oqIyeDbWnb2JK2ha1pW9matpWUfdt5Z9I5rP/4TOL7vE3u+VeivoNE+iKJ9EUS5Ys6NB0eddjytbvXsjVtK10SuzDhlAn8qdufiPRFBvUaNm507oqZMcN5svqDD0q/TdLL1q93xt0eNQr+7/8qd4yDB6F5cxhwhqJDhvL2mreJjYyl+zHd+XzM54SJ1Qp7WVnJIOR9DVX0daT0TRQqfr/q3/7m9Enzhz+obthwqCfL0hzMPagvr3xZuz3bTZmINnuymT6y6BHdm7m32mNMT1e97z6n87569VSvuUY1MlK1Rw/VnTur/XS13u7dqj17qsbEqG7ZUrVjjR+vGhaeo9yaoJO+mqTTVkxTJqJTlkypnmBNrYV1VFc3TZumGh7ufILNmqleconqY4+pLlyoeuBAyfv5/X794JcP9KyXz1ImonEPx+ktH9yiG/dtrHJMfr/qa6+ptmjhxDVihOqmTc669993kkPXrtYpX6A9e5xEEBmp+t57VT/e/TOmK6iefOVM9fv96vf79Q8v/0HjH47XTfs2Vf0EptayZFCHrVmj+swzqiNHqh57rPNpgqrP53zB/PnPqi+/7PSmWlzp4dut3+qfZv5JfQ/4NPzBcB05c6Su2LaiUrEsXap6yinO+Xv2VF20qOg2n3zi/Po9/njVlJRKnaZO2bNHtVcvJxG8+27Vj/fBLx+o7wGfNjruBz3+eH/BZ75+z3qNeShGL3j9AvWXpxhp6iRLBh7y+++qc+eq3n236plnqsbHH0oQzZqpPvyw8wVU2MZ9G3X8B+M17uE4ZSI64q0RuuvArnKdc9s21SuuUBVRPeoo1eefV83LK3n7RYucuNq1c6q4KiszJ7PyOx8B9u5VTU52uj+fO7fqx/tu+3ca/3C8Jv07Sf89NUPBKSXme/KrJ5WJ6Bvfv1H1k5layZKBh+Xmqn7/vepzz6mefbbzacfGqt58c/FfxHsz9+q9n96r4Q+G69GPH62z18wu8djp6aqPPup8sUdEqN56q2pqavniWrxYtWFDZzyIdevKt8/B3IO64LcFeufHd2rP//ZUJqLnvnqu7jxQ+xoh9u5V7d27+hLB1v1bteWkltrsyWa6OXWzpqer1q+vevnlh7bJzcvV3lN7a+JjieVO9KZusWRgCqxc6XxBhIc7VUkjRqguX150uxXbVugJ/z5BmYhe/vbluidjj/r9qmvXqv7zn07DdWSkFgzvWdagPsX59ltnlK5mzZzqrsL8fr+u2blG//XNv/T8187X2IdilYlo+IPhetoLp+nol+7SiL8eq83/cZx+vembigcQIvv2qfbp4ySCOXOqfrz0g+na67+9NPahWP1266Gh0K6/3mmj2Rtwf8Cq7as0/MFwHTVrVNVPbGqdspKB3VrqQZs3w7/+BVOnQloanHEG3HornHMO5D+CkJ2XzcSPHuXR1xYT/dsl1N80jO2bYwHo1MnpKfPii6Fv38rH8cMPzoNSqvDJJ9DmuHTe/+V9Pvz1Qz5c/2FB1xztG7fnrFbn0XzfMHas6MXH86P46aeAA4Vn0aBRLi2PjqVJE6FJE2jSxBkwqEkT5/mGtDRITXW69yjpb3q60/XHtdc61xYdXflrK05qKpx9NqxY4QyKdNFFVTtenj+PS2dcytyf5/LO8He44LgLCtZ9+63TpcUzzxze2d29n97L3xf9nQ9GfsA57c+pWgCmVrHnDEyJUlOdhDB5Mmzd6jzoNH48ZGQ4/dwsWABZWSARmWjbjzlpwF7+O34wScfXr7YY1q6F0wfkkHrgIL5R53EgYRENohpwZrszObH+YPSXc1nyWSIffeR8oUdGwumnw8CBEBcHW3Zk8Mri91m/ZR/Nw7vROrIn+/aGs3u380RvYLfOERFO1x4NGkD9+kWnIyLgnXece/6bNIHRo+Gaa5z7/6tq/34nESxfDm+9VfVEAHDL/Fv45zf/5OmBT3NjnxuLrO/VyznvzJmQlOQsy8rNovt/upOVm8UPf/6BuMi4qgdiagV7zsCU6eBB1RdfdG77zG9w7tBBddw41Q8+UN2XlqV3fXyXhj0Qps2fbK7v//J+lc+Zk5ejs9bMcm5xHddWafibRsSk673/+lHvujtPe/Q4FEuLFqrXXqs6e7ZqWlrRY+X58/SRRY9o2ANhevzTx+sPO35QVecOqv37nfGqM8vZ3pyXp/rRR6pDhx66dbdfP9VXXy3/MfKt3bVWx84dq3e994ie0OuAhoerzppVsWOU5JnFzygT0Zvev6nEbebNU23QwLmGoUNVf3DeFl20cVGZ+5q6B2szMOXl96t+9VXJbQBLUpZop2c6KRPRq965Svdl7qvwOXak79CHFj6kLSe1VCaiLSa10L9//ndd9uPvBbfHhoWpnnqq6j/+obpqVfkeqlNVXfDbAj368aM15qEYfXnlyxWOrbDt251G8vbtnbgaNXIa31evLn2/XQd26bh54zT8wXCNuidRafGlEpatza+5Ue/55B5dsW1FlW7xfHftuxr2QJgOen2Q5ubllrrtnj2q997rNPSLqA4f7rTR/PndP6tMFP1mc+1pbzFVU1YysGoiUyFZuVlM/Gwij3/1ODERMbRt2Jbm9ZvTPN591T/8b0JMAgCLtyxmytIpzFg9g+y8bM5seyY39L6BQccPIjwsHHCqdRYvdsZwqGy3FdvStjF85nAWblzIdb2uY/K5k4kOr1rlv98Pn33mVKm9/Tbk5DhVR/XqOR3C5b9E/GzP2Mbm/RvJI5tm9Y8h6kB7Nm3wMebvH7C+6eN8vvFz/Orn2EbHcmmnS7m086X0bta72P6iDmQfYM2uNfzw+w+HvbakbaFn0558Pubzclfz7N4NTz7p9H2UmQlDh2XzWZszSWy5j+XXLg961yQm9KzNwATF4pTFvLzqZVLSUtiyfwtb0rawI30HyuH/niJ9kTSu15jt6duJj4xn9Amj+XPvP9MpsVPQYsv153LPp/fw6JeP0rNpT94c8ibtG7evlmPv3Ol0E/3ll06ScF7K1tQd/LxrHZk5B2kUnUC7hu2p54tFBP7610NtBL8f+J13fnqHmWtm8slvn5Drz6Vl/ZZc2ulSejbtydrdawu+9NfvXV/wfkb5ouic2JmuR3Wl61FdubLHlQWJtqLxP/6407B8MNuPv9tL3HRbGpNHjKuW98ccuSwZmBqTk5fD9vTtbEnbUpAgtuzfwvYD2zmx+YlcnnQ58VHxNRbP3LVzGTV7FPuy9hEbEUvT+KYcE3cMTeMK/Q1YnhibWKEO3ZZsWcIt82/hy81f0iWxC0+e/WS579LZk7mHuWvnMnPNTOb/Op/svGx84uO4JscVfOnnv9o1aldQgqoO27fDY4/BU1OyycsVLh2Rzmm9G5GdDdnZTqd3+dOF530+OPpoZ3S1Y445/G+jRofuSDNHFksGxtM27tvIjNUz2Ja+zXmlbWN7+na2pW9j/8H9RbaP9EXSsn5LWjVoVfBq3aD1YfP1Iuqxcd9G7vr0Ll7//nWOij2Kvw34G1f2uLLSX9j7D+5nc+pm2jduT1R4Oca6rCbfrdtFn9Fvk71kDJp7eFVRZKTzioo6/G9OjpNMMjOLHi8i4vAEER/vVKfFxDh/C0/nz0dGQl5eYGnr8PnAaREnIZX1Cg8v38vnc25VKHyu4s4vcuh9CXxP8l/h1Zevq11Ik4GInAv8C/AB/6eqjxRaHwW8DPQCdgPDVHVDace0ZGCqS/7gL9vTt7MtzUkWKftT2Ji6kU2pm9iUuomtaVvxq/+w/RJjEtl/cD8iwl9P/iu39729Rks81e2VVa8w6s3raRrTlg5HtaJDQmuOO6otxyV0oH3j9rRr1I6YiJjD9lF1bvXdvh22bXP+Bk7n/01Pd5JGRobzNzs7RBdZQ8LCDiWGiIhDyaa0ZOS0NxU9VnHLbr0VBg+uXGxlJYOg5TER8QFTgD8AKcBSEZmjqj8GbHYVsFdV24vIcOBRoJwjvxpTNTERMbRr1K7UkcBy8nLYkraFTamb2LjvUJKI9EVyW9/baNmgZQ1GHByXJV3GgZwDfLn5S9btWcc7vy5h1/e7DtumeXxz2jduT/vG7WlRvwX1wusRHR7tvBpEE90kmtYnRHF8/rLwaKJ8UUT4IvCJD1+Yzyk1+X3kHAwn52A42VnhZB905vNyfPh8QoQvzPkbHka4O+3zHd5Qr+r8Ui/rlZt76G9Zr/zSRv458qcLL/P7nZJR4aqz4qrVCp+jpFjy8op+JiX9Rvf5gvAPwBW0koGInAxMVNVz3Pk7AVT1HwHbzHe3+VpEwoHtQKKWEpSVDIwJvn1Z+1i3Z12xrx0HdtRoLIIQJmEFLxFBkIK/xS0r/BcouGMrcL6y6wJjOyzWEtYVPkZ5ti1u3f2n38+wrpX7vRyykgHQHNgcMJ8CnFjSNqqaKyKpQBPgsJ8lInItcC1Aq1atghWvMcbVMLohyc2SSW5W9LvDr34O5h4kKzeryOtg3qHlmTmZ5PpzydM88vx5ZU6rKn71F3kph5bn+fNQ3HvjA/761V9kWf5fcJ6nAg6bL9e6ErYJXFYwX8K6wscoz7YlnaNRveANFXgEN3ccoqpTganglAxCHI4xnhYmYdSLqEe9CBvUui4J5qCoW4DACtUW7rJit3GriRrgNCQbY4ypQcFMBkuBDiLSVkQigeHAnELbzAFGu9NDgE9Lay8wxhgTHEGrJnLbAG4E5uPcWvqCqq4WkQdx+siYAzwPvCIi64A9OAnDGGNMDQtqm4GqzgPmFVp2X8B0FjA0mDEYY4wpWzCriYwxxtQSlgyMMcZYMjDGGGPJwBhjDLWw11IR2QlsrOTuCRR6urkOqGvXVNeuB+reNdW164G6d03FXU9rVU0saYdalwyqQkSWldY3R21U166prl0P1L1rqmvXA3XvmipzPVZNZIwxxpKBMcYY7yWDqaEOIAjq2jXVteuBundNde16oO5dU4Wvx1NtBsYYY4rntZKBMcaYYlgyMMYY451kICLnishaEVknIneEOp6qEpENIvK9iKwUkVo5DqiIvCAiv4vIDwHLGovIRyLyi/s3eEM7VbMSrmeiiGxxP6eVInJeKGOsKBFpKSILRORHEVktIje5y2vl51TK9dTaz0lEokVkiYiscq/pAXd5WxFZ7H7nvekOJVDycbzQZiAiPuBn4A84w28uBUao6o8hDawKRGQDkKyqtfZBGRHpB6QDL6tqV3fZY8AeVX3ETdqNVPX2UMZZXiVcz0QgXVWfCGVslSUiTYGmqvqtiMQDy4HBwBhq4edUyvX8kVr6OYkzaHKsqqaLSATwBXATcAvwtqpOF5H/AKtU9d8lHccrJYM+wDpVXa+q2cB04KIQx+R5qroQZxyLQBcBL7nTL+H8R60VSrieWk1Vt6nqt+50GrAGZ+zyWvk5lXI9tZY60t3ZCPelwBnAW+7yMj8jrySD5sDmgPkUavk/AJwP+0MRWS4i14Y6mGp0tKpuc6e3A0eHMphqcqOIfOdWI9WK6pTiiEgboAewmDrwORW6HqjFn5OI+ERkJfA78BHwK7BPVXPdTcr8zvNKMqiLTlXVnsBA4Aa3iqJOcYdAre31mP8GjgW6A9uAJ0MbTuWISBwwE7hZVfcHrquNn1Mx11OrPydVzVPV7jhjzfcBOlb0GF5JBluAlgHzLdxltZaqbnH//g7MwvkHUBfscOt18+t3fw9xPFWiqjvc/6h+4Dlq4efk1kPPBF5T1bfdxbX2cyrueurC5wSgqvuABcDJQEMRyR/NsszvPK8kg6VAB7d1PRJnrOU5IY6p0kQk1m38QkRigbOBH0rfq9aYA4x2p0cD74QwlirL/8J0XUwt+5zcxsnngTWqOilgVa38nEq6ntr8OYlIoog0dKfr4dwoswYnKQxxNyvzM/LE3UQA7q1ikwEf8IKqPhTikCpNRNrhlAbAGcf69dp4PSLyBtAfp7vdHcD9wGxgBtAKp6vyP6pqrWiULeF6+uNUPSiwAbguoK79iCcipwKLgO8Bv7v4Lpx69lr3OZVyPSOopZ+TiCThNBD7cH7gz1DVB93vielAY2AFcJmqHizxOF5JBsYYY0rmlWoiY4wxpbBkYIwxxpKBMcYYSwbGGGOwZGCMMQZLBsYUEJG8gF4rV1Zn77Yi0iawN1NjjjThZW9ijGdkuo/0G+M5VjIwpgzu2BGPueNHLBGR9u7yNiLyqdu52Sci0spdfrSIzHL7l18lIqe4h/KJyHNun/Mfuk+LIiLj3P71vxOR6SG6TONxlgyMOaReoWqiYQHrUlW1G/AMzpPsAE8DL6lqEvAa8JS7/Cngc1U9AegJrHaXdwCmqGoXYB9wqbv8DqCHe5yxwbo4Y0pjTyAb4xKRdFWNK2b5BuAMVV3vdnK2XVWbiMgunIFSctzl21Q1QUR2Ai0CH/13u0v+SFU7uPO3AxGq+ncR+QBnUJzZwOyAvumNqTFWMjCmfLSE6YoI7Bcmj0NtducDU3BKEUsDepo0psZYMjCmfIYF/P3anf4KpwdcgJE4HaABfAJcDwWDjjQo6aAiEga0VNUFwO1AA6BI6cSYYLNfIMYcUs8dLSrfB6qaf3tpIxH5DufX/Qh32V+AaSJyK7ATuMJdfhMwVUSuwikBXI8zYEpxfMCrbsIQ4Cm3T3pjapS1GRhTBrfNIFlVd4U6FmOCxaqJjDHGWMnAGGOMlQyMMcZgycAYYwyWDIwxxmDJwBhjDJYMjDHGAP8P9x/0VLFpV5oAAAAASUVORK5CYII=\n",
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ]
          },
          "metadata": {
            "tags": [],
            "needs_background": "light"
          }
        }
      ]
    }
  ]
}